In [1]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\MatMat\matmat-ademe\data\4-PlaneFR\Outputs\World\SSP1_2050\extensions\ghg_emissions\F_x_dom.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
df

region                     AT                                  \
sector             Paddy rice         Wheat Cereal grains nec
source         gas
ghg_combustion CO2        0.0  1.023734e-01      1.177140e-01
               CH4        0.0  3.949579e-04      4.537343e-04
               N2O        0.0  2.977763e-03      3.418267e-03
               SF6        0.0  0.000000e+00      0.000000e+00
               HFC        0.0  0.000000e+00      0.000000e+00
               PFC        0.0  0.000000e+00      0.000000e+00
ghg_other      CO2        0.0  6.733024e-03      9.693368e-03
               CH4        0.0  1.694463e-09      1.512201e-09
               N2O        0.0  2.442438e-01      3.540981e-01
               SF6        0.0  1.994092e-03      4.099676e-03
               HFC        0.0  1.094943e-02      2.298061e-02
               PFC        0.0  2.639835e-04      5.592177e-04

region                                                    \
sector             Vegetables, fruit, nuts     Oil seeds
source         gas
ghg_combustion CO2            1.282180e-01  4.583596e-02
               CH4            4.727748e-04  1.742998e-04
               N2O            3.477382e-03  1.302362e-03
               SF6            0.000000e+00  0.000000e+00
               HFC            0.000000e+00  0.000000e+00
               PFC            0.000000e+00  0.000000e+00
ghg_other      CO2            4.044297e-03  3.625596e-03
               CH4            2.053027e-07  2.312251e-08
               N2O            1.037412e-01  1.132956e-01
               SF6            3.439295e-03  3.996193e-04
               HFC            2.042221e-02  2.098950e-03
               PFC            5.932657e-04  4.472649e-05

region                                                                      \
sector             Sugar cane, sugar beet Plant-based fibers     Crops nec
source         gas
ghg_combustion CO2           1.281986e-02       1.138353e-04  5.745192e-02
               CH4           4.870507e-05       4.230889e-07  2.214518e-04
               N2O           3.642661e-04       3.115823e-06  1.668342e-03
               SF6           0.000000e+00       0.000000e+00  0.000000e+00
               HFC           0.000000e+00       0.000000e+00  0.000000e+00
               PFC           0.000000e+00       0.000000e+00  0.000000e+00
ghg_other      CO2           1.152114e-03       1.852317e-05  4.726968e-03
               CH4           1.553030e-07       2.059438e-10  9.102362e-10
               N2O           5.552528e-02       4.863285e-04  1.726708e-01
               SF6           3.873916e-03       0.000000e+00  2.005814e-03
               HFC           1.919630e-02       0.000000e+00  1.124160e-02
               PFC           4.701880e-04       0.000000e+00  2.735586e-04

region                                  ...                            WM  \
sector                Cattle      Pigs  ... Paper for treatment: landfill
source         gas                      ...
ghg_combustion CO2  0.123079  0.050483  ...                      0.990952
               CH4  0.000471  0.000183  ...                      0.002560
               N2O  0.003549  0.001334  ...                      0.006117
               SF6  0.000000  0.000000  ...                      0.000000
               HFC  0.000000  0.000000  ...                      0.000000
               PFC  0.000000  0.000000  ...                      0.000000
ghg_other      CO2  0.020778  0.000039  ...                      0.102066
               CH4  1.969148  0.162236  ...                     36.096263
               N2O  0.400611  0.168166  ...                      0.001531
               SF6  0.000690  0.001305  ...                      0.000174
               HFC  0.004504  0.007121  ...                      0.001046
               PFC  0.000106  0.000174  ...                      0.000150

region                                                    \
sector             Plastic waste for treatment: landfill
source         gas
ghg_combustion CO2                              0.650254
               CH4                              0.001689
               N2O                              0.003246
               SF6                              0.000000
               HFC                              0.000000
               PFC                              0.000000
ghg_other      CO2                              0.086415
               CH4                              1.144398
               N2O                              0.002018
               SF6                              0.000195
               HFC                              0.001245
               PFC                              0.000026

region                                                                  \
sector             Inert/metal/hazardous waste for treatment: landfill
source         gas
ghg_combustion CO2                                           0.933669
               CH4                                           0.002372
               N2O                                           0.005497
               SF6                                           0.000000
               HFC                                           0.000000
               PFC                                           0.000000
ghg_other      CO2                                           0.085450
               CH4                                           0.264631
               N2O                                           0.001401
               SF6                                           0.000179
               HFC                                           0.000800
               PFC                                           0.000348

region                                                     \
sector             Textiles waste for treatment: landfill
source         gas
ghg_combustion CO2                               0.261706
               CH4                               0.000746
               N2O                               0.001432
               SF6                               0.000000
               HFC                               0.000000
               PFC                               0.000000
ghg_other      CO2                               0.052186
               CH4                               4.052084
               N2O                               0.002334
               SF6                               0.000129
               HFC                               0.000808
               PFC                               0.000064

region                                                 \
sector             Wood waste for treatment: landfill
source         gas
ghg_combustion CO2                           0.356612
               CH4                           0.000958
               N2O                           0.001833
               SF6                           0.000000
               HFC                           0.000000
               PFC                           0.000000
ghg_other      CO2                           0.073413
               CH4                           0.877323
               N2O                           0.002179
               SF6                           0.000141
               HFC                           0.000874
               PFC                           0.000084

region                                                           \
sector             Membership organisation services n.e.c. (91)
source         gas
ghg_combustion CO2                                     0.500447
               CH4                                     0.002178
               N2O                                     0.003943
               SF6                                     0.000000
               HFC                                     0.000000
               PFC                                     0.000000
ghg_other      CO2                                     0.014366
               CH4                                     0.161468
               N2O                                     0.002741
               SF6                                     0.001049
               HFC                                     0.007311
               PFC                                     0.000264

region                                                                \
sector             Recreational, cultural and sporting services (92)
source         gas
ghg_combustion CO2                                          1.235412
               CH4                                          0.007575
               N2O                                          0.011210
               SF6                                          0.000000
               HFC                                          0.000000
               PFC                                          0.000000
ghg_other      CO2                                          0.025042
               CH4                                          0.266514
               N2O                                          0.011259
               SF6                                          0.002559
               HFC                                          0.017414
               PFC                                          0.000437

region                                  \
sector             Other services (93)
source         gas
ghg_combustion CO2            3.184395
               CH4            0.011228
               N2O            0.028070
               SF6            0.000000
               HFC            0.000000
               PFC            0.000000
ghg_other      CO2            0.092299
               CH4            0.259913
               N2O            0.001790
               SF6            0.002543
               HFC            0.016565
               PFC            0.000575

region                                                            \
sector             Private households with employed persons (95)
source         gas
ghg_combustion CO2                                      1.222940
               CH4                                      0.005919
               N2O                                      0.012291
               SF6                                      0.000000
               HFC                                      0.000000
               PFC                                      0.000000
ghg_other      CO2                                      0.001859
               CH4                                      0.026807
               N2O                                      0.010970
               SF6                                      0.001143
               HFC                                      0.007343
               PFC                                      0.000020

region
sector             Extra-territorial organizations and bodies
source         gas
ghg_combustion CO2                                        0.0
               CH4                                        0.0
               N2O                                        0.0
               SF6                                        0.0
               HFC                                        0.0
               PFC                                        0.0
ghg_other      CO2                                        0.0
               CH4                                        0.0
               N2O                                        0.0
               SF6                                        0.0
               HFC                                        0.0
               PFC                                        0.0

[12 rows x 9800 columns]

In [ ]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\Module_PlaneFR\data\3.11.2\2015\extensions\dom_raw_materials\M.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
df

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Arnaud\\Documents\\CIRED\\PlaneFR\\Code\\Module_PlaneFR\\data\\3.10.2\\2015\\extensions\\dom_raw_materials\\M.pkl'

In [2]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\MatMat\matmat-ademe\data\4-PlaneFR\1-accounts\Exiobase\3.10.2_2019\3.10.2_pxp_2019\extensions\water\F_x_dom.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
# exporte en csv
df['FR'].to_excel(r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Données\Exiobase\F_X_water_310.xlsx")
df['FR']

sector,Paddy rice,Wheat,Cereal grains nec,"Vegetables, fruit, nuts",Oil seeds,"Sugar cane, sugar beet",Plant-based fibers,Crops nec,Cattle,Pigs,...,Paper for treatment: landfill,Plastic waste for treatment: landfill,Inert/metal/hazardous waste for treatment: landfill,Textiles waste for treatment: landfill,Wood waste for treatment: landfill,Membership organisation services n.e.c. (91),"Recreational, cultural and sporting services (92)",Other services (93),Private households with employed persons (95),Extra-territorial organizations and bodies
indicator,,,,,,,,,,,,,,,,,,,,,
Water Consumption Blue - Agriculture - rice,122.381,0.0000,0.00,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Water Consumption Blue - Agriculture - wheat,0.000,46.3867,0.00,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Water Consumption Blue - Agriculture - other cereals,0.000,0.0000,1239.38,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Water Consumption Blue - Agriculture - roots and tubers,0.000,0.0000,0.00,0.0,0.0,0.0000,0.0,116.084,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Water Consumption Blue - Agriculture - sugar crops,0.000,0.0000,0.00,0.0,0.0,40.5079,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Water Consumption Blue - Electricity - once-through - Electricity by solar thermal,0.000,0.0000,0.00,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Water Consumption Blue - Electricity - once-through - Electricity by tide, wave, ocean",0.000,0.0000,0.00,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Water Consumption Blue - Electricity - once-through - Electricity by Geothermal,0.000,0.0000,0.00,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Water Consumption Blue - Electricity - once-through - Electricity nec,0.000,0.0000,0.00,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Water Consumption Blue - Domestic - domestic Water Consumption Blue,0.000,0.0000,0.00,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
import pickle
PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\MatMat\matmat-ademe\data\4-PlaneFR\Outputs\World\Base_year_2015\extensions\land\S_x_dom.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
# exporte en csv
#df['FR'].to_excel(r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Données\Exiobase\F_x_dom_materials.xlsx")
df

region                                                     AT            \
sector                                             Paddy rice     Wheat
indicator
Artificial Surfaces                                       0.0  0.000000
Cropland - cropped area - Cereal grains nec               0.0  0.000000
Cropland - cropped area - Crops nec                       0.0  0.000000
Cropland - cropped area - Oil seeds                       0.0  0.000000
Cropland - cropped area - Paddy rice                      0.0  0.000000
Cropland - cropped area - Plant-based fibers              0.0  0.000000
Cropland - cropped area - Sugar cane, sugar beet          0.0  0.000000
Cropland - cropped area - Vegetables, fruit, nuts         0.0  0.000000
Cropland - cropped area - Wheat                           0.0  9.730714
Cropland - fallowed area - Cereal grains nec              0.0  0.000000
Cropland - fallowed area - Crops nec                      0.0  0.000000
Cropland - fallowed area - Oil seeds                      0.0  0.000000
Cropland - fallowed area - Paddy rice                     0.0  0.000000
Cropland - fallowed area - Plant-based fibers             0.0  0.000000
Cropland - fallowed area - Sugar cane, sugar beet         0.0  0.000000
Cropland - fallowed area - Vegetables, fruit, nuts        0.0  0.000000
Cropland - fallowed area - Wheat                          0.0  0.940372
Cropland - fallowed area-Cattle                           0.0  0.000000
Cropland - fallowed area-Meat animals nec                 0.0  0.000000
Cropland - fallowed area-Pigs                             0.0  0.000000
Cropland - fallowed area-Poultry                          0.0  0.000000
Cropland - fallowed area-Raw milk                         0.0  0.000000
Naturally generating forest - Non primary forest          0.0  0.000000
Permanent pastures - Grazing-Cattle                       0.0  0.000000
Permanent pastures - Grazing-Meat animals nec             0.0  0.000000
Permanent pastures - Grazing-Raw milk                     0.0  0.000000
Planted forest                                            0.0  0.000000

region                                                                \
sector                                             Cereal grains nec
indicator
Artificial Surfaces                                         0.000000
Cropland - cropped area - Cereal grains nec                 8.191312
Cropland - cropped area - Crops nec                         0.000000
Cropland - cropped area - Oil seeds                         0.000000
Cropland - cropped area - Paddy rice                        0.000000
Cropland - cropped area - Plant-based fibers                0.000000
Cropland - cropped area - Sugar cane, sugar beet            0.000000
Cropland - cropped area - Vegetables, fruit, nuts           0.000000
Cropland - cropped area - Wheat                             0.000000
Cropland - fallowed area - Cereal grains nec                0.791605
Cropland - fallowed area - Crops nec                        0.000000
Cropland - fallowed area - Oil seeds                        0.000000
Cropland - fallowed area - Paddy rice                       0.000000
Cropland - fallowed area - Plant-based fibers               0.000000
Cropland - fallowed area - Sugar cane, sugar beet           0.000000
Cropland - fallowed area - Vegetables, fruit, nuts          0.000000
Cropland - fallowed area - Wheat                            0.000000
Cropland - fallowed area-Cattle                             0.000000
Cropland - fallowed area-Meat animals nec                   0.000000
Cropland - fallowed area-Pigs                               0.000000
Cropland - fallowed area-Poultry                            0.000000
Cropland - fallowed area-Raw milk                           0.000000
Naturally generating forest - Non primary forest            0.000000
Permanent pastures - Grazing-Cattle                         0.000000
Permanent pastures - Grazing-Meat animals nec               0.000000
Permanent pastures - Grazing-Raw milk                       0.000000
Planted forest                                              0.000000

region                                                                      \
sector                                             Vegetables, fruit, nuts
indicator
Artificial Surfaces                                               0.000000
Cropland - cropped area - Cereal grains nec                       0.000000
Cropland - cropped area - Crops nec                               0.000000
Cropland - cropped area - Oil seeds                               0.000000
Cropland - cropped area - Paddy rice                              0.000000
Cropland - cropped area - Plant-based fibers                      0.000000
Cropland - cropped area - Sugar cane, sugar beet                  0.000000
Cropland - cropped area - Vegetables, fruit, nuts                 0.677295
Cropland - cropped area - Wheat                                   0.000000
Cropland - fallowed area - Cereal grains nec                      0.000000
Cropland - fallowed area - Crops nec                              0.000000
Cropland - fallowed area - Oil seeds                              0.000000
Cropland - fallowed area - Paddy rice                             0.000000
Cropland - fallowed area - Plant-based fibers                     0.000000
Cropland - fallowed area - Sugar cane, sugar beet                 0.000000
Cropland - fallowed area - Vegetables, fruit, nuts                0.065454
Cropland - fallowed area - Wheat                                  0.000000
Cropland - fallowed area-Cattle                                   0.000000
Cropland - fallowed area-Meat animals nec                         0.000000
Cropland - fallowed area-Pigs                                     0.000000
Cropland - fallowed area-Poultry                                  0.000000
Cropland - fallowed area-Raw milk                                 0.000000
Naturally generating forest - Non primary forest                  0.000000
Permanent pastures - Grazing-Cattle                               0.000000
Permanent pastures - Grazing-Meat animals nec                     0.000000
Permanent pastures - Grazing-Raw milk                             0.000000
Planted forest                                                    0.000000

region                                                        \
sector                                             Oil seeds
indicator
Artificial Surfaces                                 0.000000
Cropland - cropped area - Cereal grains nec         0.000000
Cropland - cropped area - Crops nec                 0.000000
Cropland - cropped area - Oil seeds                 6.366922
Cropland - cropped area - Paddy rice                0.000000
Cropland - cropped area - Plant-based fibers        0.000000
Cropland - cropped area - Sugar cane, sugar beet    0.000000
Cropland - cropped area - Vegetables, fruit, nuts   0.000000
Cropland - cropped area - Wheat                     0.000000
Cropland - fallowed area - Cereal grains nec        0.000000
Cropland - fallowed area - Crops nec                0.000000
Cropland - fallowed area - Oil seeds                0.615297
Cropland - fallowed area - Paddy rice               0.000000
Cropland - fallowed area - Plant-based fibers       0.000000
Cropland - fallowed area - Sugar cane, sugar beet   0.000000
Cropland - fallowed area - Vegetables, fruit, nuts  0.000000
Cropland - fallowed area - Wheat                    0.000000
Cropland - fallowed area-Cattle                     0.000000
Cropland - fallowed area-Meat animals nec           0.000000
Cropland - fallowed area-Pigs                       0.000000
Cropland - fallowed area-Poultry                    0.000000
Cropland - fallowed area-Raw milk                   0.000000
Naturally generating forest - Non primary forest    0.000000
Permanent pastures - Grazing-Cattle                 0.000000
Permanent pastures - Grazing-Meat animals nec       0.000000
Permanent pastures - Grazing-Raw milk               0.000000
Planted forest                                      0.000000

region                                                                     \
sector                                             Sugar cane, sugar beet
indicator
Artificial Surfaces                                              0.000000
Cropland - cropped area - Cereal grains nec                      0.000000
Cropland - cropped area - Crops nec                              0.000000
Cropland - cropped area - Oil seeds                              0.000000
Cropland - cropped area - Paddy rice                             0.000000
Cropland - cropped area - Plant-based fibers                     0.000000
Cropland - cropped area - Sugar cane, sugar beet                 4.430293
Cropland - cropped area - Vegetables, fruit, nuts                0.000000
Cropland - cropped area - Wheat                                  0.000000
Cropland - fallowed area - Cereal grains nec                     0.000000
Cropland - fallowed area - Crops nec                             0.000000
Cropland - fallowed area - Oil seeds                             0.000000
Cropland - fallowed area - Paddy rice                            0.000000
Cropland - fallowed area - Plant-based fibers                    0.000000
Cropland - fallowed area - Sugar cane, sugar beet                0.428142
Cropland - fallowed area - Vegetables, fruit, nuts               0.000000
Cropland - fallowed area - Wheat                                 0.000000
Cropland - fallowed area-Cattle                                  0.000000
Cropland - fallowed area-Meat animals nec                        0.000000
Cropland - fallowed area-Pigs                                    0.000000
Cropland - fallowed area-Poultry                                 0.000000
Cropland - fallowed area-Raw milk                                0.000000
Naturally generating forest - Non primary forest                 0.000000
Permanent pastures - Grazing-Cattle                              0.000000
Permanent pastures - Grazing-Meat animals nec                    0.000000
Permanent pastures - Grazing-Raw milk                            0.000000
Planted forest                                                   0.000000

region                                                                 \
sector                                             Plant-based fibers
indicator
Artificial Surfaces                                          0.000000
Cropland - cropped area - Cereal grains nec                  0.000000
Cropland - cropped area - Crops nec                          0.000000
Cropland - cropped area - Oil seeds                          0.000000
Cropland - cropped area - Paddy rice                         0.000000
Cropland - cropped area - Plant-based fibers                 8.601491
Cropland - cropped area - Sugar cane, sugar beet             0.000000
Cropland - cropped area - Vegetables, fruit, nuts            0.000000
Cropland - cropped area - Wheat                              0.000000
Cropland - fallowed area - Cereal grains nec                 0.000000
Cropland - fallowed area - Crops nec                         0.000000
Cropland - fallowed area - Oil seeds                         0.000000
Cropland - fallowed area - Paddy rice                        0.000000
Cropland - fallowed area - Plant-based fibers                0.831245
Cropland - fallowed area - Sugar cane, sugar beet            0.000000
Cropland - fallowed area - Vegetables, fruit, nuts           0.000000
Cropland - fallowed area - Wheat                             0.000000
Cropland - fallowed area-Cattle                              0.000000
Cropland - fallowed area-Meat animals nec                    0.000000
Cropland - fallowed area-Pigs                                0.000000
Cropland - fallowed area-Poultry                             0.000000
Cropland - fallowed area-Raw milk                            0.000000
Naturally generating forest - Non primary forest             0.000000
Permanent pastures - Grazing-Cattle                          0.000000
Permanent pastures - Grazing-Meat animals nec                0.000000
Permanent pastures - Grazing-Raw milk                        0.000000
Planted forest                                               0.000000

region                                                                   \
sector                                             Crops nec     Cattle
indicator
Artificial Surfaces                                 0.000000   0.000000
Cropland - cropped area - Cereal grains nec         0.000000   0.000000
Cropland - cropped area - Crops nec                 0.008458   0.000000
Cropland - cropped area - Oil seeds                 0.000000   0.000000
Cropland - cropped area - Paddy rice                0.000000   0.000000
Cropland - cropped area - Plant-based fibers        0.000000   0.000000
Cropland - cropped area - Sugar cane, sugar beet    0.000000   0.000000
Cropland - cropped area - Vegetables, fruit, nuts   0.000000   0.000000
Cropland - cropped area - Wheat                     0.000000   0.000000
Cropland - fallowed area - Cereal grains nec        0.000000   0.000000
Cropland - fallowed area - Crops nec                0.000817   0.000000
Cropland - fallowed area - Oil seeds                0.000000   0.000000
Cropland - fallowed area - Paddy rice               0.000000   0.000000
Cropland - fallowed area - Plant-based fibers       0.000000   0.000000
Cropland - fallowed area - Sugar cane, sugar beet   0.000000   0.000000
Cropland - fallowed area - Vegetables, fruit, nuts  0.000000   0.000000
Cropland - fallowed area - Wheat                    0.000000   0.000000
Cropland - fallowed area-Cattle                     0.000000   1.742314
Cropland - fallowed area-Meat animals nec           0.000000   0.000000
Cropland - fallowed area-Pigs                       0.000000   0.000000
Cropland - fallowed area-Poultry                    0.000000   0.000000
Cropland - fallowed area-Raw milk                   0.000000   0.000000
Naturally generating forest - Non primary forest    0.000000   0.000000
Permanent pastures - Grazing-Cattle                 0.000000  12.162408
Permanent pastures - Grazing-Meat animals nec       0.000000   0.000000
Permanent pastures - Grazing-Raw milk               0.000000   0.000000
Planted forest                                      0.000000   0.000000

region                                                        ...  \
sector                                                  Pigs  ...
indicator                                                     ...
Artificial Surfaces                                 0.000000  ...
Cropland - cropped area - Cereal grains nec         0.000000  ...
Cropland - cropped area - Crops nec                 0.000000  ...
Cropland - cropped area - Oil seeds                 0.000000  ...
Cropland - cropped area - Paddy rice                0.000000  ...
Cropland - cropped area - Plant-based fibers        0.000000  ...
Cropland - cropped area - Sugar cane, sugar beet    0.000000  ...
Cropland - cropped area - Vegetables, fruit, nuts   0.000000  ...
Cropland - cropped area - Wheat                     0.000000  ...
Cropland - fallowed area - Cereal grains nec        0.000000  ...
Cropland - fallowed area - Crops nec                0.000000  ...
Cropland - fallowed area - Oil seeds                0.000000  ...
Cropland - fallowed area - Paddy rice               0.000000  ...
Cropland - fallowed area - Plant-based fibers       0.000000  ...
Cropland - fallowed area - Sugar cane, sugar beet   0.000000  ...
Cropland - fallowed area - Vegetables, fruit, nuts  0.000000  ...
Cropland - fallowed area - Wheat                    0.000000  ...
Cropland - fallowed area-Cattle                     0.000000  ...
Cropland - fallowed area-Meat animals nec           0.000000  ...
Cropland - fallowed area-Pigs                       0.290414  ...
Cropland - fallowed area-Poultry                    0.000000  ...
Cropland - fallowed area-Raw milk                   0.000000  ...
Naturally generating forest - Non primary forest    0.000000  ...
Permanent pastures - Grazing-Cattle                 0.000000  ...
Permanent pastures - Grazing-Meat animals nec       0.000000  ...
Permanent pastures - Grazing-Raw milk               0.000000  ...
Planted forest                                      0.000000  ...

region                                                                        WM  \
sector                                             Paper for treatment: landfill
indicator
Artificial Surfaces                                                          0.0
Cropland - cropped area - Cereal grains nec                                  0.0
Cropland - cropped area - Crops nec                                          0.0
Cropland - cropped area - Oil seeds                                          0.0
Cropland - cropped area - Paddy rice                                         0.0
Cropland - cropped area - Plant-based fibers                                 0.0
Cropland - cropped area - Sugar cane, sugar beet                             0.0
Cropland - cropped area - Vegetables, fruit, nuts                            0.0
Cropland - cropped area - Wheat                                              0.0
Cropland - fallowed area - Cereal grains nec                                 0.0
Cropland - fallowed area - Crops nec                                         0.0
Cropland - fallowed area - Oil seeds                                         0.0
Cropland - fallowed area - Paddy rice                                        0.0
Cropland - fallowed area - Plant-based fibers                                0.0
Cropland - fallowed area - Sugar cane, sugar beet                            0.0
Cropland - fallowed area - Vegetables, fruit, nuts                           0.0
Cropland - fallowed area - Wheat                                             0.0
Cropland - fallowed area-Cattle                                              0.0
Cropland - fallowed area-Meat animals nec                                    0.0
Cropland - fallowed area-Pigs                                                0.0
Cropland - fallowed area-Poultry                                             0.0
Cropland - fallowed area-Raw milk                                            0.0
Naturally generating forest - Non primary forest                             0.0
Permanent pastures - Grazing-Cattle                                          0.0
Permanent pastures - Grazing-Meat animals nec                                0.0
Permanent pastures - Grazing-Raw milk                                        0.0
Planted forest                                                               0.0

region                                                                                    \
sector                                             Plastic waste for treatment: landfill
indicator
Artificial Surfaces                                                                  0.0
Cropland - cropped area - Cereal grains nec                                          0.0
Cropland - cropped area - Crops nec                                                  0.0
Cropland - cropped area - Oil seeds                                                  0.0
Cropland - cropped area - Paddy rice                                                 0.0
Cropland - cropped area - Plant-based fibers                                         0.0
Cropland - cropped area - Sugar cane, sugar beet                                     0.0
Cropland - cropped area - Vegetables, fruit, nuts                                    0.0
Cropland - cropped area - Wheat                                                      0.0
Cropland - fallowed area - Cereal grains nec                                         0.0
Cropland - fallowed area - Crops nec                                                 0.0

In [ ]:
PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\Module_PlaneFR\data\3.10.2\2019_World\extensions\raw_materials\d_cba.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
# exporte en csv
#df['FR'].to_excel(r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Données\Exiobase\F_x_dom_materials.xlsx")
df

region                                                     World
Y_category                                                   all
sector                                                       all
indicator
Primary Crops - Rice                                7.532864e+05
Primary Crops - Wheat                               7.640759e+05
Primary Crops - Cereals n.e.c.                      1.446088e+06
Primary Crops - Roots and tubers                    8.535042e+05
Primary Crops - Pulses                              8.541811e+04
...                                                          ...
Non-Metallic Minerals - Chemical minerals n.e.c.    2.026269e+05
Non-Metallic Minerals - Industrial minerals n.e.c   4.264276e+05
Non-Metallic Minerals - Salt                        2.714749e+05
Non-Metallic Minerals - Other non-metallic mine...  3.161830e+05
RMC                                                 9.481321e+07

[63 rows x 1 columns]

In [ ]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\MatMat\matmat-ademe\data\4-PlaneFR\Outputs\World\base-year_2019\extensions\land_use\F_x_dom.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
df_tot_exio = df['FR'].sum().sum()
df_tot_exio

np.float64(456884.4815233743)

In [ ]:
1 - df_tot_exio / df_tot_matmat

np.float64(-0.0242570833859288)