In [3]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\Module_PlaneFR\data\3.11.2\S1_2050\extensions\imp_land\M_RoW.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
df

region                                                       RoW            \
category                                             Agriculture
sub_category                                       Primary_Crops
sector                                                Paddy rice     Wheat
indicator
Artificial Surfaces                                     0.000000  0.000000
Cropland - cropped area - Cereal grains nec             0.007563  0.003815
Cropland - cropped area - Crops nec                     0.001268  0.000606
Cropland - cropped area - Oil seeds                     0.008127  0.049695
Cropland - cropped area - Paddy rice                    5.077722  0.001332
Cropland - cropped area - Plant-based fibers            0.000933  0.000203
Cropland - cropped area - Sugar cane, sugar beet        0.003719  0.000478
Cropland - cropped area - Vegetables, fruit, nuts       0.001109  0.001840
Cropland - cropped area - Wheat                         0.007931  4.177947
Cropland - fallowed area - Cereal grains nec            0.001798  0.000675
Cropland - fallowed area - Crops nec                    0.000279  0.000088
Cropland - fallowed area - Oil seeds                    0.001465  0.009541
Cropland - fallowed area - Paddy rice                   1.103516  0.000134
Cropland - fallowed area - Plant-based fibers           0.000210  0.000048
Cropland - fallowed area - Sugar cane, sugar beet       0.001225  0.000106
Cropland - fallowed area - Vegetables, fruit, nuts      0.000275  0.000375
Cropland - fallowed area - Wheat                        0.002064  0.509100
Cropland - fallowed area-Cattle                         0.003850  0.001386
Cropland - fallowed area-Meat animals nec               0.000214  0.000150
Cropland - fallowed area-Pigs                           0.000212  0.000285
Cropland - fallowed area-Poultry                        0.000425  0.000175
Cropland - fallowed area-Raw milk                       0.001103  0.000892
Naturally generating forest - Non primary forest        0.175452  0.057817
Permanent pastures - Grazing-Cattle                     0.129079  0.014347
Permanent pastures - Grazing-Meat animals nec           0.011659  0.006102
Permanent pastures - Grazing-Raw milk                   0.031542  0.005785
Planted forest                                          0.009691  0.011198

region                                                                \
category
sub_category
sector                                             Cereal grains nec
indicator
Artificial Surfaces                                         0.000000
Cropland - cropped area - Cereal grains nec                 3.473885
Cropland - cropped area - Crops nec                         0.000512
Cropland - cropped area - Oil seeds                         0.008305
Cropland - cropped area - Paddy rice                        0.002085
Cropland - cropped area - Plant-based fibers                0.000250
Cropland - cropped area - Sugar cane, sugar beet            0.003091
Cropland - cropped area - Vegetables, fruit, nuts           0.000817
Cropland - cropped area - Wheat                             0.014733
Cropland - fallowed area - Cereal grains nec                0.580055
Cropland - fallowed area - Crops nec                        0.000090
Cropland - fallowed area - Oil seeds                        0.001541
Cropland - fallowed area - Paddy rice                       0.000212
Cropland - fallowed area - Plant-based fibers               0.000055
Cropland - fallowed area - Sugar cane, sugar beet           0.000902
Cropland - fallowed area - Vegetables, fruit, nuts          0.000160
Cropland - fallowed area - Wheat                            0.004174
Cropland - fallowed area-Cattle                             0.001391
Cropland - fallowed area-Meat animals nec                   0.000095
Cropland - fallowed area-Pigs                               0.000140
Cropland - fallowed area-Poultry                            0.000157
Cropland - fallowed area-Raw milk                           0.000572
Naturally generating forest - Non primary forest            0.033463
Permanent pastures - Grazing-Cattle                         0.036420
Permanent pastures - Grazing-Meat animals nec               0.003447
Permanent pastures - Grazing-Raw milk                       0.007672
Planted forest                                              0.005045

region                                                                      \
category
sub_category
sector                                             Vegetables, fruit, nuts
indicator
Artificial Surfaces                                               0.000000
Cropland - cropped area - Cereal grains nec                       0.014741
Cropland - cropped area - Crops nec                               0.001281
Cropland - cropped area - Oil seeds                               0.017055
Cropland - cropped area - Paddy rice                              0.003740
Cropland - cropped area - Plant-based fibers                      0.001096
Cropland - cropped area - Sugar cane, sugar beet                  0.001527
Cropland - cropped area - Vegetables, fruit, nuts                 2.401854
Cropland - cropped area - Wheat                                   0.014485
Cropland - fallowed area - Cereal grains nec                      0.003250
Cropland - fallowed area - Crops nec                              0.000198
Cropland - fallowed area - Oil seeds                              0.003276
Cropland - fallowed area - Paddy rice                             0.000431
Cropland - fallowed area - Plant-based fibers                     0.000258
Cropland - fallowed area - Sugar cane, sugar beet                 0.000382
Cropland - fallowed area - Vegetables, fruit, nuts                0.604096
Cropland - fallowed area - Wheat                                  0.004202
Cropland - fallowed area-Cattle                                   0.002305
Cropland - fallowed area-Meat animals nec                         0.000487
Cropland - fallowed area-Pigs                                     0.000348
Cropland - fallowed area-Poultry                                  0.000320
Cropland - fallowed area-Raw milk                                 0.000941
Naturally generating forest - Non primary forest                  0.206239
Permanent pastures - Grazing-Cattle                               0.057294
Permanent pastures - Grazing-Meat animals nec                     0.023837
Permanent pastures - Grazing-Raw milk                             0.021292
Planted forest                                                    0.021371

region                                                        \
category
sub_category
sector                                             Oil seeds
indicator
Artificial Surfaces                                 0.000000
Cropland - cropped area - Cereal grains nec         0.005695
Cropland - cropped area - Crops nec                 0.000623
Cropland - cropped area - Oil seeds                 6.645875
Cropland - cropped area - Paddy rice                0.003315
Cropland - cropped area - Plant-based fibers        0.000451
Cropland - cropped area - Sugar cane, sugar beet    0.001014
Cropland - cropped area - Vegetables, fruit, nuts   0.002253
Cropland - cropped area - Wheat                     0.004268
Cropland - fallowed area - Cereal grains nec        0.001062
Cropland - fallowed area - Crops nec                0.000111
Cropland - fallowed area - Oil seeds                0.958126
Cropland - fallowed area - Paddy rice               0.000328
Cropland - fallowed area - Plant-based fibers       0.000098
Cropland - fallowed area - Sugar cane, sugar beet   0.000279
Cropland - fallowed area - Vegetables, fruit, nuts  0.000420
Cropland - fallowed area - Wheat                    0.001049
Cropland - fallowed area-Cattle                     0.002194
Cropland - fallowed area-Meat animals nec           0.000222
Cropland - fallowed area-Pigs                       0.000250
Cropland - fallowed area-Poultry                    0.000322
Cropland - fallowed area-Raw milk                   0.001151
Naturally generating forest - Non primary forest    0.072899
Permanent pastures - Grazing-Cattle                 0.050992
Permanent pastures - Grazing-Meat animals nec       0.006841
Permanent pastures - Grazing-Raw milk               0.011139
Planted forest                                      0.008015

region                                                                     \
category
sub_category
sector                                             Sugar cane, sugar beet
indicator
Artificial Surfaces                                              0.000000
Cropland - cropped area - Cereal grains nec                      0.005713
Cropland - cropped area - Crops nec                              0.000417
Cropland - cropped area - Oil seeds                              0.004784
Cropland - cropped area - Paddy rice                             0.034823
Cropland - cropped area - Plant-based fibers                     0.000496
Cropland - cropped area - Sugar cane, sugar beet                 1.791292
Cropland - cropped area - Vegetables, fruit, nuts                0.000983
Cropland - cropped area - Wheat                                  0.009519
Cropland - fallowed area - Cereal grains nec                     0.001374
Cropland - fallowed area - Crops nec                             0.000062
Cropland - fallowed area - Oil seeds                             0.000909
Cropland - fallowed area - Paddy rice                            0.002849
Cropland - fallowed area - Plant-based fibers                    0.000107
Cropland - fallowed area - Sugar cane, sugar beet                0.474604
Cropland - fallowed area - Vegetables, fruit, nuts               0.000241
Cropland - fallowed area - Wheat                                 0.003449
Cropland - fallowed area-Cattle                                  0.000701
Cropland - fallowed area-Meat animals nec                        0.000148
Cropland - fallowed area-Pigs                                    0.000110
Cropland - fallowed area-Poultry                                 0.000114
Cropland - fallowed area-Raw milk                                0.000297
Naturally generating forest - Non primary forest                 0.034703
Permanent pastures - Grazing-Cattle                              0.020734
Permanent pastures - Grazing-Meat animals nec                    0.008762
Permanent pastures - Grazing-Raw milk                            0.006193
Planted forest                                                   0.004265

region                                                                 \
category
sub_category
sector                                             Plant-based fibers
indicator
Artificial Surfaces                                          0.000000
Cropland - cropped area - Cereal grains nec                  0.083951
Cropland - cropped area - Crops nec                          0.006788
Cropland - cropped area - Oil seeds                          0.079100
Cropland - cropped area - Paddy rice                         0.101298
Cropland - cropped area - Plant-based fibers                10.804748
Cropland - cropped area - Sugar cane, sugar beet             0.013218
Cropland - cropped area - Vegetables, fruit, nuts            0.012359
Cropland - cropped area - Wheat                              0.052160
Cropland - fallowed area - Cereal grains nec                 0.015951
Cropland - fallowed area - Crops nec                         0.000915
Cropland - fallowed area - Oil seeds                         0.014208
Cropland - fallowed area - Paddy rice                        0.008982
Cropland - fallowed area - Plant-based fibers                2.285850
Cropland - fallowed area - Sugar cane, sugar beet            0.003312
Cropland - fallowed area - Vegetables, fruit, nuts           0.002768
Cropland - fallowed area - Wheat                             0.015521
Cropland - fallowed area-Cattle                              0.022214
Cropland - fallowed area-Meat animals nec                    0.004117
Cropland - fallowed area-Pigs                                0.004650
Cropland - fallowed area-Poultry                             0.006207
Cropland - fallowed area-Raw milk                            0.007848
Naturally generating forest - Non primary forest             0.479242
Permanent pastures - Grazing-Cattle                          0.643758
Permanent pastures - Grazing-Meat animals nec                0.295382
Permanent pastures - Grazing-Raw milk                        0.230459
Planted forest                                               0.033647

region                                                                     \
category
sub_category                                                 Farm_animals
sector                                             Crops nec       Cattle
indicator
Artificial Surfaces                                 0.000000     0.000000
Cropland - cropped area - Cereal grains nec         0.043796     1.659088
Cropland - cropped area - Crops nec                 3.833718     0.323253
Cropland - cropped area - Oil seeds                 0.024949     0.329190
Cropland - cropped area - Paddy rice                0.048090     0.017288
Cropland - cropped area - Plant-based fibers        0.001562     0.001683
Cropland - cropped area - Sugar cane, sugar beet    0.005942     0.011988
Cropland - cropped area - Vegetables, fruit, nuts   0.003535     0.072173
Cropland - cropped area - Wheat                     0.024822     0.602925
Cropland - fallowed area - Cereal grains nec        0.008189     0.402662
Cropland - fallowed area - Crops nec                0.563237     0.048299
Cropland - fallowed area - Oil seeds                0.004990     0.065716
Cropland - fallowed area - Paddy rice               0.004504     0.002813
Cropland - fallowed area - Plant-based fibers       0.000332     0.000409
Cropland - fallowed area - Sugar cane, sugar beet   0.001361     0.002562
Cropland - fallowed area - Vegetables, fruit, nuts  0.000791     0.018044
Cropland - fallowed area - Wheat                    0.007490     0.149030
Cropland - fallowed area-Cattle                     0.005231     3.669287
Cropland - fallowed area-Meat animals nec           0.000593     0.001332
Cropland - fallowed area-Pigs                       0.000503     0.003511
Cropland - fallowed area-Poultry                    0.000554     0.000876
Cropland - fallowed area-Raw milk                   0.002470     0.024598
Naturally generating forest - Non primary forest    0.621910     0.569587
Permanent pastures - Grazing-Cattle                 0.157871    46.623694
Permanent pastures - Grazing-Meat animals nec       0.024335     0.045232
Permanent pastures - Grazing-Raw milk               0.030717     0.287035
Planted forest                                      0.040049     0.106674

region                                                        ...  \
category                                                      ...
sub_category                                                  ...
sector                                                  Pigs  ...
indicator                                                     ...
Artificial Surfaces                                 0.000000  ...
Cropland - cropped area - Cereal grains nec         0.500447  ...
Cropland - cropped area - Crops nec                 0.069987  ...
Cropland - cropped area - Oil seeds                 0.309479  ...
Cropland - cropped area - Paddy rice                0.008215  ...
Cropland - cropped area - Plant-based fibers        0.000837  ...
Cropland - cropped area - Sugar cane, sugar beet    0.019410  ...
Cropland - cropped area - Vegetables, fruit, nuts   0.124156  ...
Cropland - cropped area - Wheat                     0.161630  ...
Cropland - fallowed area - Cereal grains nec        0.064941  ...
Cropland - fallowed area - Crops nec                0.009822  ...
Cropland - fallowed area - Oil seeds                0.057378  ...
Cropland - fallowed area - Paddy rice               0.001345  ...
Cropland - fallowed area - Plant-based fibers       0.000206  ...
Cropland - fallowed area - Sugar cane, sugar beet   0.004733  ...
Cropland - fallowed area - Vegetables, fruit, nuts  0.033088  ...
Cropland - fallowed area - Wheat                    0.028320  ...
Cropland - fallowed area-Cattle                     0.016900  ...
Cropland - fallowed area-Meat animals nec           0.016946  ...
Cropland - fallowed area-Pigs                       0.625359  ...
Cropland - fallowed area-Poultry                    0.000741  ...
Cropland - fallowed area-Raw milk                   0.048084  ...
Naturally generating forest - Non primary forest    0.305285  ...
Permanent pastures - Grazing-Cattle                 0.192462  ...
Permanent pastures - Grazing-Meat animals nec       0.536542  ...
Permanent pastures - Grazing-Raw milk               0.159199  ...
Planted forest                                      0.103529  ...

region                                                                            \
category                                               Water_and_waste_treatment
sub_category                                                            Landfill
sector                                             Paper for treatment: landfill
indicator
Artificial Surfaces                                                     0.000000
Cropland - cropped area - Cereal grains nec                             0.173265
Cropland - cropped area - Crops nec                                     0.016336
Cropland - cropped area - Oil seeds                                     0.117249
Cropland - cropped area - Paddy rice                                    0.503397
Cropland - cropped area - Plant-based fibers                            0.003218
Cropland - cropped area - Sugar cane, sugar beet                        0.048783
Cropland - cropped area - Vegetables, fruit, nuts                       0.017997
Cropland - cropped area - Wheat                                         0.218426
Cropland - fallowed area - Cereal grains nec                            0.040304
Cropland - fallowed area - Crops nec                                    0.002567
Cropland - fallowed area - Oil seeds                                    0.022667
Cropland - fallowed area - Paddy rice                                   0.041163
Cropland - fallowed area - Plant-based fibers                           0.000698
Cropland - fallowed area - Sugar cane, sugar beet                       0.012717
Cropland - fallowed area - Vegetables, fruit, nuts                      0.004123
Cropland - fallowed area - Wheat                                        0.067581
Cropland - fallowed area-Cattle                                         0.044095
Cropland - fallowed area-Meat animals nec                               0.004305
Cropland - fallowed area-Pigs                                           0.017119
Cropland - fallowed area-Poultry                                        0.017607
Cropland - fallowed area-Raw milk                                       0.009776
Naturally generating forest - Non primary forest                        0.514888
Permanent pastures - Grazing-Cattle                                     1.391018
Permanent pastures - Grazing-Meat animals nec                           0.281228
Permanent pastures - Grazing-Raw milk                                   0.279848
Planted forest                                                          0.067440

region                                                                                    \
category
sub_category
sector                                             Plastic waste for treatment: landfill
indicator
Artificial Surfaces                                                             0.000000
Cropland - cropped area - Cereal grains nec                                     0.365690
Cropland - cropped area - Crops nec                                             0.035457

In [ ]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\Module_PlaneFR\data\3.11.2\2015\extensions\dom_raw_materials\M.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
df

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Arnaud\\Documents\\CIRED\\PlaneFR\\Code\\Module_PlaneFR\\data\\3.10.2\\2015\\extensions\\dom_raw_materials\\M.pkl'

In [2]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\MatMat\matmat-ademe\data\4-PlaneFR\1-accounts\Exiobase\3.10.2_2019\3.10.2_pxp_2019\extensions\water\F_x_dom.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
# exporte en csv
df['FR'].to_excel(r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Données\Exiobase\F_X_water_310.xlsx")
df['FR']

sector,Paddy rice,Wheat,Cereal grains nec,"Vegetables, fruit, nuts",Oil seeds,"Sugar cane, sugar beet",Plant-based fibers,Crops nec,Cattle,Pigs,...,Paper for treatment: landfill,Plastic waste for treatment: landfill,Inert/metal/hazardous waste for treatment: landfill,Textiles waste for treatment: landfill,Wood waste for treatment: landfill,Membership organisation services n.e.c. (91),"Recreational, cultural and sporting services (92)",Other services (93),Private households with employed persons (95),Extra-territorial organizations and bodies
indicator,,,,,,,,,,,,,,,,,,,,,
Water Consumption Blue - Agriculture - rice,122.381,0.0000,0.00,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Water Consumption Blue - Agriculture - wheat,0.000,46.3867,0.00,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Water Consumption Blue - Agriculture - other cereals,0.000,0.0000,1239.38,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Water Consumption Blue - Agriculture - roots and tubers,0.000,0.0000,0.00,0.0,0.0,0.0000,0.0,116.084,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Water Consumption Blue - Agriculture - sugar crops,0.000,0.0000,0.00,0.0,0.0,40.5079,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Water Consumption Blue - Electricity - once-through - Electricity by solar thermal,0.000,0.0000,0.00,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Water Consumption Blue - Electricity - once-through - Electricity by tide, wave, ocean",0.000,0.0000,0.00,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Water Consumption Blue - Electricity - once-through - Electricity by Geothermal,0.000,0.0000,0.00,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Water Consumption Blue - Electricity - once-through - Electricity nec,0.000,0.0000,0.00,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Water Consumption Blue - Domestic - domestic Water Consumption Blue,0.000,0.0000,0.00,0.0,0.0,0.0000,0.0,0.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
import pickle
PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\MatMat\matmat-ademe\data\4-PlaneFR\Outputs\World\Base_year_2015\extensions\land\S_x_dom.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
# exporte en csv
#df['FR'].to_excel(r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Données\Exiobase\F_x_dom_materials.xlsx")
df

region                                                     AT            \
sector                                             Paddy rice     Wheat
indicator
Artificial Surfaces                                       0.0  0.000000
Cropland - cropped area - Cereal grains nec               0.0  0.000000
Cropland - cropped area - Crops nec                       0.0  0.000000
Cropland - cropped area - Oil seeds                       0.0  0.000000
Cropland - cropped area - Paddy rice                      0.0  0.000000
Cropland - cropped area - Plant-based fibers              0.0  0.000000
Cropland - cropped area - Sugar cane, sugar beet          0.0  0.000000
Cropland - cropped area - Vegetables, fruit, nuts         0.0  0.000000
Cropland - cropped area - Wheat                           0.0  9.730714
Cropland - fallowed area - Cereal grains nec              0.0  0.000000
Cropland - fallowed area - Crops nec                      0.0  0.000000
Cropland - fallowed area - Oil seeds                      0.0  0.000000
Cropland - fallowed area - Paddy rice                     0.0  0.000000
Cropland - fallowed area - Plant-based fibers             0.0  0.000000
Cropland - fallowed area - Sugar cane, sugar beet         0.0  0.000000
Cropland - fallowed area - Vegetables, fruit, nuts        0.0  0.000000
Cropland - fallowed area - Wheat                          0.0  0.940372
Cropland - fallowed area-Cattle                           0.0  0.000000
Cropland - fallowed area-Meat animals nec                 0.0  0.000000
Cropland - fallowed area-Pigs                             0.0  0.000000
Cropland - fallowed area-Poultry                          0.0  0.000000
Cropland - fallowed area-Raw milk                         0.0  0.000000
Naturally generating forest - Non primary forest          0.0  0.000000
Permanent pastures - Grazing-Cattle                       0.0  0.000000
Permanent pastures - Grazing-Meat animals nec             0.0  0.000000
Permanent pastures - Grazing-Raw milk                     0.0  0.000000
Planted forest                                            0.0  0.000000

region                                                                \
sector                                             Cereal grains nec
indicator
Artificial Surfaces                                         0.000000
Cropland - cropped area - Cereal grains nec                 8.191312
Cropland - cropped area - Crops nec                         0.000000
Cropland - cropped area - Oil seeds                         0.000000
Cropland - cropped area - Paddy rice                        0.000000
Cropland - cropped area - Plant-based fibers                0.000000
Cropland - cropped area - Sugar cane, sugar beet            0.000000
Cropland - cropped area - Vegetables, fruit, nuts           0.000000
Cropland - cropped area - Wheat                             0.000000
Cropland - fallowed area - Cereal grains nec                0.791605
Cropland - fallowed area - Crops nec                        0.000000
Cropland - fallowed area - Oil seeds                        0.000000
Cropland - fallowed area - Paddy rice                       0.000000
Cropland - fallowed area - Plant-based fibers               0.000000
Cropland - fallowed area - Sugar cane, sugar beet           0.000000
Cropland - fallowed area - Vegetables, fruit, nuts          0.000000
Cropland - fallowed area - Wheat                            0.000000
Cropland - fallowed area-Cattle                             0.000000
Cropland - fallowed area-Meat animals nec                   0.000000
Cropland - fallowed area-Pigs                               0.000000
Cropland - fallowed area-Poultry                            0.000000
Cropland - fallowed area-Raw milk                           0.000000
Naturally generating forest - Non primary forest            0.000000
Permanent pastures - Grazing-Cattle                         0.000000
Permanent pastures - Grazing-Meat animals nec               0.000000
Permanent pastures - Grazing-Raw milk                       0.000000
Planted forest                                              0.000000

region                                                                      \
sector                                             Vegetables, fruit, nuts
indicator
Artificial Surfaces                                               0.000000
Cropland - cropped area - Cereal grains nec                       0.000000
Cropland - cropped area - Crops nec                               0.000000
Cropland - cropped area - Oil seeds                               0.000000
Cropland - cropped area - Paddy rice                              0.000000
Cropland - cropped area - Plant-based fibers                      0.000000
Cropland - cropped area - Sugar cane, sugar beet                  0.000000
Cropland - cropped area - Vegetables, fruit, nuts                 0.677295
Cropland - cropped area - Wheat                                   0.000000
Cropland - fallowed area - Cereal grains nec                      0.000000
Cropland - fallowed area - Crops nec                              0.000000
Cropland - fallowed area - Oil seeds                              0.000000
Cropland - fallowed area - Paddy rice                             0.000000
Cropland - fallowed area - Plant-based fibers                     0.000000
Cropland - fallowed area - Sugar cane, sugar beet                 0.000000
Cropland - fallowed area - Vegetables, fruit, nuts                0.065454
Cropland - fallowed area - Wheat                                  0.000000
Cropland - fallowed area-Cattle                                   0.000000
Cropland - fallowed area-Meat animals nec                         0.000000
Cropland - fallowed area-Pigs                                     0.000000
Cropland - fallowed area-Poultry                                  0.000000
Cropland - fallowed area-Raw milk                                 0.000000
Naturally generating forest - Non primary forest                  0.000000
Permanent pastures - Grazing-Cattle                               0.000000
Permanent pastures - Grazing-Meat animals nec                     0.000000
Permanent pastures - Grazing-Raw milk                             0.000000
Planted forest                                                    0.000000

region                                                        \
sector                                             Oil seeds
indicator
Artificial Surfaces                                 0.000000
Cropland - cropped area - Cereal grains nec         0.000000
Cropland - cropped area - Crops nec                 0.000000
Cropland - cropped area - Oil seeds                 6.366922
Cropland - cropped area - Paddy rice                0.000000
Cropland - cropped area - Plant-based fibers        0.000000
Cropland - cropped area - Sugar cane, sugar beet    0.000000
Cropland - cropped area - Vegetables, fruit, nuts   0.000000
Cropland - cropped area - Wheat                     0.000000
Cropland - fallowed area - Cereal grains nec        0.000000
Cropland - fallowed area - Crops nec                0.000000
Cropland - fallowed area - Oil seeds                0.615297
Cropland - fallowed area - Paddy rice               0.000000
Cropland - fallowed area - Plant-based fibers       0.000000
Cropland - fallowed area - Sugar cane, sugar beet   0.000000
Cropland - fallowed area - Vegetables, fruit, nuts  0.000000
Cropland - fallowed area - Wheat                    0.000000
Cropland - fallowed area-Cattle                     0.000000
Cropland - fallowed area-Meat animals nec           0.000000
Cropland - fallowed area-Pigs                       0.000000
Cropland - fallowed area-Poultry                    0.000000
Cropland - fallowed area-Raw milk                   0.000000
Naturally generating forest - Non primary forest    0.000000
Permanent pastures - Grazing-Cattle                 0.000000
Permanent pastures - Grazing-Meat animals nec       0.000000
Permanent pastures - Grazing-Raw milk               0.000000
Planted forest                                      0.000000

region                                                                     \
sector                                             Sugar cane, sugar beet
indicator
Artificial Surfaces                                              0.000000
Cropland - cropped area - Cereal grains nec                      0.000000
Cropland - cropped area - Crops nec                              0.000000
Cropland - cropped area - Oil seeds                              0.000000
Cropland - cropped area - Paddy rice                             0.000000
Cropland - cropped area - Plant-based fibers                     0.000000
Cropland - cropped area - Sugar cane, sugar beet                 4.430293
Cropland - cropped area - Vegetables, fruit, nuts                0.000000
Cropland - cropped area - Wheat                                  0.000000
Cropland - fallowed area - Cereal grains nec                     0.000000
Cropland - fallowed area - Crops nec                             0.000000
Cropland - fallowed area - Oil seeds                             0.000000
Cropland - fallowed area - Paddy rice                            0.000000
Cropland - fallowed area - Plant-based fibers                    0.000000
Cropland - fallowed area - Sugar cane, sugar beet                0.428142
Cropland - fallowed area - Vegetables, fruit, nuts               0.000000
Cropland - fallowed area - Wheat                                 0.000000
Cropland - fallowed area-Cattle                                  0.000000
Cropland - fallowed area-Meat animals nec                        0.000000
Cropland - fallowed area-Pigs                                    0.000000
Cropland - fallowed area-Poultry                                 0.000000
Cropland - fallowed area-Raw milk                                0.000000
Naturally generating forest - Non primary forest                 0.000000
Permanent pastures - Grazing-Cattle                              0.000000
Permanent pastures - Grazing-Meat animals nec                    0.000000
Permanent pastures - Grazing-Raw milk                            0.000000
Planted forest                                                   0.000000

region                                                                 \
sector                                             Plant-based fibers
indicator
Artificial Surfaces                                          0.000000
Cropland - cropped area - Cereal grains nec                  0.000000
Cropland - cropped area - Crops nec                          0.000000
Cropland - cropped area - Oil seeds                          0.000000
Cropland - cropped area - Paddy rice                         0.000000
Cropland - cropped area - Plant-based fibers                 8.601491
Cropland - cropped area - Sugar cane, sugar beet             0.000000
Cropland - cropped area - Vegetables, fruit, nuts            0.000000
Cropland - cropped area - Wheat                              0.000000
Cropland - fallowed area - Cereal grains nec                 0.000000
Cropland - fallowed area - Crops nec                         0.000000
Cropland - fallowed area - Oil seeds                         0.000000
Cropland - fallowed area - Paddy rice                        0.000000
Cropland - fallowed area - Plant-based fibers                0.831245
Cropland - fallowed area - Sugar cane, sugar beet            0.000000
Cropland - fallowed area - Vegetables, fruit, nuts           0.000000
Cropland - fallowed area - Wheat                             0.000000
Cropland - fallowed area-Cattle                              0.000000
Cropland - fallowed area-Meat animals nec                    0.000000
Cropland - fallowed area-Pigs                                0.000000
Cropland - fallowed area-Poultry                             0.000000
Cropland - fallowed area-Raw milk                            0.000000
Naturally generating forest - Non primary forest             0.000000
Permanent pastures - Grazing-Cattle                          0.000000
Permanent pastures - Grazing-Meat animals nec                0.000000
Permanent pastures - Grazing-Raw milk                        0.000000
Planted forest                                               0.000000

region                                                                   \
sector                                             Crops nec     Cattle
indicator
Artificial Surfaces                                 0.000000   0.000000
Cropland - cropped area - Cereal grains nec         0.000000   0.000000
Cropland - cropped area - Crops nec                 0.008458   0.000000
Cropland - cropped area - Oil seeds                 0.000000   0.000000
Cropland - cropped area - Paddy rice                0.000000   0.000000
Cropland - cropped area - Plant-based fibers        0.000000   0.000000
Cropland - cropped area - Sugar cane, sugar beet    0.000000   0.000000
Cropland - cropped area - Vegetables, fruit, nuts   0.000000   0.000000
Cropland - cropped area - Wheat                     0.000000   0.000000
Cropland - fallowed area - Cereal grains nec        0.000000   0.000000
Cropland - fallowed area - Crops nec                0.000817   0.000000
Cropland - fallowed area - Oil seeds                0.000000   0.000000
Cropland - fallowed area - Paddy rice               0.000000   0.000000
Cropland - fallowed area - Plant-based fibers       0.000000   0.000000
Cropland - fallowed area - Sugar cane, sugar beet   0.000000   0.000000
Cropland - fallowed area - Vegetables, fruit, nuts  0.000000   0.000000
Cropland - fallowed area - Wheat                    0.000000   0.000000
Cropland - fallowed area-Cattle                     0.000000   1.742314
Cropland - fallowed area-Meat animals nec           0.000000   0.000000
Cropland - fallowed area-Pigs                       0.000000   0.000000
Cropland - fallowed area-Poultry                    0.000000   0.000000
Cropland - fallowed area-Raw milk                   0.000000   0.000000
Naturally generating forest - Non primary forest    0.000000   0.000000
Permanent pastures - Grazing-Cattle                 0.000000  12.162408
Permanent pastures - Grazing-Meat animals nec       0.000000   0.000000
Permanent pastures - Grazing-Raw milk               0.000000   0.000000
Planted forest                                      0.000000   0.000000

region                                                        ...  \
sector                                                  Pigs  ...
indicator                                                     ...
Artificial Surfaces                                 0.000000  ...
Cropland - cropped area - Cereal grains nec         0.000000  ...
Cropland - cropped area - Crops nec                 0.000000  ...
Cropland - cropped area - Oil seeds                 0.000000  ...
Cropland - cropped area - Paddy rice                0.000000  ...
Cropland - cropped area - Plant-based fibers        0.000000  ...
Cropland - cropped area - Sugar cane, sugar beet    0.000000  ...
Cropland - cropped area - Vegetables, fruit, nuts   0.000000  ...
Cropland - cropped area - Wheat                     0.000000  ...
Cropland - fallowed area - Cereal grains nec        0.000000  ...
Cropland - fallowed area - Crops nec                0.000000  ...
Cropland - fallowed area - Oil seeds                0.000000  ...
Cropland - fallowed area - Paddy rice               0.000000  ...
Cropland - fallowed area - Plant-based fibers       0.000000  ...
Cropland - fallowed area - Sugar cane, sugar beet   0.000000  ...
Cropland - fallowed area - Vegetables, fruit, nuts  0.000000  ...
Cropland - fallowed area - Wheat                    0.000000  ...
Cropland - fallowed area-Cattle                     0.000000  ...
Cropland - fallowed area-Meat animals nec           0.000000  ...
Cropland - fallowed area-Pigs                       0.290414  ...
Cropland - fallowed area-Poultry                    0.000000  ...
Cropland - fallowed area-Raw milk                   0.000000  ...
Naturally generating forest - Non primary forest    0.000000  ...
Permanent pastures - Grazing-Cattle                 0.000000  ...
Permanent pastures - Grazing-Meat animals nec       0.000000  ...
Permanent pastures - Grazing-Raw milk               0.000000  ...
Planted forest                                      0.000000  ...

region                                                                        WM  \
sector                                             Paper for treatment: landfill
indicator
Artificial Surfaces                                                          0.0
Cropland - cropped area - Cereal grains nec                                  0.0
Cropland - cropped area - Crops nec                                          0.0
Cropland - cropped area - Oil seeds                                          0.0
Cropland - cropped area - Paddy rice                                         0.0
Cropland - cropped area - Plant-based fibers                                 0.0
Cropland - cropped area - Sugar cane, sugar beet                             0.0
Cropland - cropped area - Vegetables, fruit, nuts                            0.0
Cropland - cropped area - Wheat                                              0.0
Cropland - fallowed area - Cereal grains nec                                 0.0
Cropland - fallowed area - Crops nec                                         0.0
Cropland - fallowed area - Oil seeds                                         0.0
Cropland - fallowed area - Paddy rice                                        0.0
Cropland - fallowed area - Plant-based fibers                                0.0
Cropland - fallowed area - Sugar cane, sugar beet                            0.0
Cropland - fallowed area - Vegetables, fruit, nuts                           0.0
Cropland - fallowed area - Wheat                                             0.0
Cropland - fallowed area-Cattle                                              0.0
Cropland - fallowed area-Meat animals nec                                    0.0
Cropland - fallowed area-Pigs                                                0.0
Cropland - fallowed area-Poultry                                             0.0
Cropland - fallowed area-Raw milk                                            0.0
Naturally generating forest - Non primary forest                             0.0
Permanent pastures - Grazing-Cattle                                          0.0
Permanent pastures - Grazing-Meat animals nec                                0.0
Permanent pastures - Grazing-Raw milk                                        0.0
Planted forest                                                               0.0

region                                                                                    \
sector                                             Plastic waste for treatment: landfill
indicator
Artificial Surfaces                                                                  0.0
Cropland - cropped area - Cereal grains nec                                          0.0
Cropland - cropped area - Crops nec                                                  0.0
Cropland - cropped area - Oil seeds                                                  0.0
Cropland - cropped area - Paddy rice                                                 0.0
Cropland - cropped area - Plant-based fibers                                         0.0
Cropland - cropped area - Sugar cane, sugar beet                                     0.0
Cropland - cropped area - Vegetables, fruit, nuts                                    0.0
Cropland - cropped area - Wheat                                                      0.0
Cropland - fallowed area - Cereal grains nec                                         0.0
Cropland - fallowed area - Crops nec                                                 0.0

In [ ]:
PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\Module_PlaneFR\data\3.10.2\2019_World\extensions\raw_materials\d_cba.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
# exporte en csv
#df['FR'].to_excel(r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Données\Exiobase\F_x_dom_materials.xlsx")
df

region                                                     World
Y_category                                                   all
sector                                                       all
indicator
Primary Crops - Rice                                7.532864e+05
Primary Crops - Wheat                               7.640759e+05
Primary Crops - Cereals n.e.c.                      1.446088e+06
Primary Crops - Roots and tubers                    8.535042e+05
Primary Crops - Pulses                              8.541811e+04
...                                                          ...
Non-Metallic Minerals - Chemical minerals n.e.c.    2.026269e+05
Non-Metallic Minerals - Industrial minerals n.e.c   4.264276e+05
Non-Metallic Minerals - Salt                        2.714749e+05
Non-Metallic Minerals - Other non-metallic mine...  3.161830e+05
RMC                                                 9.481321e+07

[63 rows x 1 columns]

In [ ]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\MatMat\matmat-ademe\data\4-PlaneFR\Outputs\World\base-year_2019\extensions\land_use\F_x_dom.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
df_tot_exio = df['FR'].sum().sum()
df_tot_exio

np.float64(456884.4815233743)

In [ ]:
1 - df_tot_exio / df_tot_matmat

np.float64(-0.0242570833859288)