In [1]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\Module_PlaneFR\data\3.10.2\2015\system\Y.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
df

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Arnaud\\Documents\\CIRED\\PlaneFR\\Code\\Module_PlaneFR\\data\\3.10.2\\2015\\system\\Y.pkl'

In [ ]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\Module_PlaneFR\data\3.10.2\2015\extensions\dom_raw_materials\d_cba.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
df

region                                                   France        \
Y_category                                           Households
Y_sub_category                                      Residential
category                                            Agriculture
sub_category                                      Primary_Crops
sector                                               Paddy rice Wheat
indicator
Paddy rice                                                  0.0   0.0
Wheat                                                       0.0   0.0
Cereal grains nec                                           0.0   0.0
Vegetables, fruit, nuts                                     0.0   0.0
Oil seeds                                                   0.0   0.0
...                                                         ...   ...
Recreational, cultural and sporting services (92)           0.0   0.0
Other services (93)                                         0.0   0.0
Private households with employed persons (95)               0.0   0.0
Extra-territorial organizations and bodies                  0.0   0.0
RMC                                                         0.0   0.0

region                                                               \
Y_category
Y_sub_category
category
sub_category
sector                                            Cereal grains nec
indicator
Paddy rice                                                      0.0
Wheat                                                           0.0
Cereal grains nec                                               0.0
Vegetables, fruit, nuts                                         0.0
Oil seeds                                                       0.0
...                                                             ...
Recreational, cultural and sporting services (92)               0.0
Other services (93)                                             0.0
Private households with employed persons (95)                   0.0
Extra-territorial organizations and bodies                      0.0
RMC                                                             0.0

region                                                                     \
Y_category
Y_sub_category
category
sub_category
sector                                            Vegetables, fruit, nuts
indicator
Paddy rice                                                            0.0
Wheat                                                                 0.0
Cereal grains nec                                                     0.0
Vegetables, fruit, nuts                                               0.0
Oil seeds                                                             0.0
...                                                                   ...
Recreational, cultural and sporting services (92)                     0.0
Other services (93)                                                   0.0
Private households with employed persons (95)                         0.0
Extra-territorial organizations and bodies                            0.0
RMC                                                                   0.0

region                                                       \
Y_category
Y_sub_category
category
sub_category
sector                                            Oil seeds
indicator
Paddy rice                                              0.0
Wheat                                                   0.0
Cereal grains nec                                       0.0
Vegetables, fruit, nuts                                 0.0
Oil seeds                                               0.0
...                                                     ...
Recreational, cultural and sporting services (92)       0.0
Other services (93)                                     0.0
Private households with employed persons (95)           0.0
Extra-territorial organizations and bodies              0.0
RMC                                                     0.0

region                                                                    \
Y_category
Y_sub_category
category
sub_category
sector                                            Sugar cane, sugar beet
indicator
Paddy rice                                                           0.0
Wheat                                                                0.0
Cereal grains nec                                                    0.0
Vegetables, fruit, nuts                                              0.0
Oil seeds                                                            0.0
...                                                                  ...
Recreational, cultural and sporting services (92)                    0.0
Other services (93)                                                  0.0
Private households with employed persons (95)                        0.0
Extra-territorial organizations and bodies                           0.0
RMC                                                                  0.0

region                                                                \
Y_category
Y_sub_category
category
sub_category
sector                                            Plant-based fibers
indicator
Paddy rice                                                       0.0
Wheat                                                            0.0
Cereal grains nec                                                0.0
Vegetables, fruit, nuts                                          0.0
Oil seeds                                                        0.0
...                                                              ...
Recreational, cultural and sporting services (92)                0.0
Other services (93)                                              0.0
Private households with employed persons (95)                    0.0
Extra-territorial organizations and bodies                       0.0
RMC                                                              0.0

region                                                                         \
Y_category
Y_sub_category
category
sub_category                                                Farm_animals
sector                                            Crops nec       Cattle Pigs
indicator
Paddy rice                                              0.0          0.0  0.0
Wheat                                                   0.0          0.0  0.0
Cereal grains nec                                       0.0          0.0  0.0
Vegetables, fruit, nuts                                 0.0          0.0  0.0
Oil seeds                                               0.0          0.0  0.0
...                                                     ...          ...  ...
Recreational, cultural and sporting services (92)       0.0          0.0  0.0
Other services (93)                                     0.0          0.0  0.0
Private households with employed persons (95)           0.0          0.0  0.0
Extra-territorial organizations and bodies              0.0          0.0  0.0
RMC                                                     0.0          0.0  0.0

region                                             ...  \
Y_category                                         ...
Y_sub_category                                     ...
category                                           ...
sub_category                                       ...
sector                                             ...
indicator                                          ...
Paddy rice                                         ...
Wheat                                              ...
Cereal grains nec                                  ...
Vegetables, fruit, nuts                            ...
Oil seeds                                          ...
...                                                ...
Recreational, cultural and sporting services (92)  ...
Other services (93)                                ...
Private households with employed persons (95)      ...
Extra-territorial organizations and bodies         ...
RMC                                                ...

region                                                                           \
Y_category                                                              Exports
Y_sub_category                                                                E
category                                              Water_and_waste_treatment
sub_category                                                           Landfill
sector                                            Paper for treatment: landfill
indicator
Paddy rice                                                             0.000022
Wheat                                                                  0.006420
Cereal grains nec                                                      0.011196
Vegetables, fruit, nuts                                                0.002669
Oil seeds                                                              0.002146
...                                                                         ...
Recreational, cultural and sporting services (92)                      0.000000
Other services (93)                                                    0.000000
Private households with employed persons (95)                          0.000000
Extra-territorial organizations and bodies                             0.000000
RMC                                                                    1.395783

region                                                                                   \
Y_category
Y_sub_category
category
sub_category
sector                                            Plastic waste for treatment: landfill
indicator
Paddy rice                                                                     0.000006
Wheat                                                                          0.001798
Cereal grains nec                                                              0.003103
Vegetables, fruit, nuts                                                        0.000733
Oil seeds                                                                      0.000592
...                                                                                 ...
Recreational, cultural and sporting services (92)                              0.000000
Other services (93)                                                            0.000000
Private households with employed persons (95)                                  0.000000
Extra-territorial organizations and bodies                                     0.000000
RMC                                                                            0.323070

region                                                                                                 \
Y_category
Y_sub_category
category
sub_category
sector                                            Inert/metal/hazardous waste for treatment: landfill
indicator
Paddy rice                                                                                  0.000054
Wheat                                                                                       0.015451
Cereal grains nec                                                                           0.026974
Vegetables, fruit, nuts                                                                     0.006462
Oil seeds                                                                                   0.005201
...                                                                                               ...
Recreational, cultural and sporting services (92)                                           0.000000
Other services (93)                                                                         0.000000
Private households with employed persons (95)                                               0.000000
Extra-territorial organizations and bodies                                                  0.000000
RMC                                                                                         3.905884

region                                                                                    \
Y_category
Y_sub_category
category
sub_category
sector                                            Textiles waste for treatment: landfill
indicator
Paddy rice                                                                      0.000004
Wheat                                                                           0.001240
Cereal grains nec                                                               0.002134
Vegetables, fruit, nuts                                                         0.000502
Oil seeds                                                                       0.000407
...                                                                                  ...
Recreational, cultural and sporting services (92)                               0.000000
Other services (93)                                                             0.000000
Private households with employed persons (95)                                   0.000000
Extra-territorial organizations and bodies                                      0.000000
RMC                                                                             0.206496

region                                                                                \
Y_category
Y_sub_category
category
sub_category
sector                                            Wood waste for treatment: landfill
indicator
Paddy rice                                                                  0.000009
Wheat                                                                       0.002596
Cereal grains nec                                                           0.004532
Vegetables, fruit, nuts                                                     0.001075
Oil seeds                                                                   0.000866
...                                                                              ...
Recreational, cultural and sporting services (92)                           0.000000
Other services (93)                                                         0.000000
Private households with employed persons (95)                               0.000000
Extra-territorial organizations and bodies                                  0.000000
RMC                                                                         0.515570

region                                                                                          \
Y_category
Y_sub_category
category                                                                          Oth_services
sub_category                                                                 Business_services
sector                                            Membership organisation services n.e.c. (91)
indicator
Paddy rice                                                                            0.000157
Wheat                                                                                 0.037445
Cereal grains nec                                                                     0.076721
Vegetables, fruit, nuts                                                               0.019716
Oil seeds                                                                             0.014257
...                                                                                        ...
Recreational, cultural and sporting services (92)                                     0.000000
Other services (93)                                                                   0.000000
Private households with employed persons (95)                                         0.000000
Extra-territorial organizations and bodies                                            0.000000
RMC                                                                                   4.043170

region                                                                                               \
Y_category
Y_sub_category
category
sub_category
sector                                            Recreational, cultural and sporting services (92)
indicator
Paddy rice                                                                                 0.017011
Wheat                                                                                      4.129446
Cereal grains nec                                                                          8.369957
Vegetables, fruit, nuts                                                                    2.014261
Oil seeds                                                                                  1.624440
...                                                                                             ...
Recreational, cultural and sporting services (92)                                          0.000000
Other services (93)                                                                        0.000000
Private households with employed persons (95)                                              0.000000
Extra-territorial organizations and bodies                                                 0.000000
RMC                                                                                      241.867356

region                                                                 \
Y_category
Y_sub_category
category
sub_category
sector                                            Other services (93)
indicator
Paddy rice                                                   0.000100
Wheat                                                        0.022807
Cereal grains nec                                            0.045096
Vegetables, fruit, nuts                                      0.011336
Oil seeds                                                    0.009062
...                                                               ...
Recreational, cultural and sporting services (92)            0.000000
Other services (93)                                          0.000000
Private households with employed persons (95)                0.000000
Extra-territorial organizations and bodies                   0.000000
RMC                                                          3.446642

region                                                                                           \
Y_category
Y_sub_category
category
sub_category
sector                                            Private households with employed persons (95)
indicator
Paddy rice                                                                         2.381847e-07
Wheat                                                                              6.519145e-05
Cereal grains nec                                                                  1.117642e-04
Vegetables, fruit, nuts                                                            2.872963e-05
Oil seeds                                                                          2.266297e-05
...                                                                                         ...
Recreational, cultural and sporting services (92)                                  0.000000e+00
Other services (93)                                                                0.000000e+00
Private households with employed persons (95)                                      0.000000e+00
Extra-territorial organizations and bodies                                         0.000000e+00
RMC                                                                                2.017425e+01

region
Y_category
Y_sub_category
category
sub_category
sector                                            Extra-territorial organizations and bodies
indicator
Paddy rice                                                                               0.0
Wheat                                                                                    0.0
Cereal grains nec                                                                        0.0

In [3]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\MatMat\matmat-ademe\data\4-PlaneFR\1-accounts\Exiobase\3.10.2_2019\3.10.2_pxp_2019\extensions\land_use\F_x_dom.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
# exporte en csv
df['FR'].to_excel(r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Données\Exiobase\F_X_land_310.xlsx")
df['FR']

sector,Paddy rice,Wheat,Cereal grains nec,"Vegetables, fruit, nuts",Oil seeds,"Sugar cane, sugar beet",Plant-based fibers,Crops nec,Cattle,Pigs,...,Paper for treatment: landfill,Plastic waste for treatment: landfill,Inert/metal/hazardous waste for treatment: landfill,Textiles waste for treatment: landfill,Wood waste for treatment: landfill,Membership organisation services n.e.c. (91),"Recreational, cultural and sporting services (92)",Other services (93),Private households with employed persons (95),Extra-territorial organizations and bodies
indicator,,,,,,,,,,,,,,,,,,,,,
Artificial Surfaces,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - cropped area - Cereal grains nec,0.00000,0.000000,41974.290000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - cropped area - Crops nec,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,35.920000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - cropped area - Oil seeds,0.00000,0.000000,0.000000,0.000000,19227.220000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - cropped area - Paddy rice,151.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - cropped area - Plant-based fibers,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,145.500000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Cropland - cropped area - Sugar cane, sugar beet",0.00000,0.000000,0.000000,0.000000,0.000000,4466.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Cropland - cropped area - Vegetables, fruit, nuts",0.00000,0.000000,0.000000,17740.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - cropped area - Wheat,0.00000,52442.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - fallowed area - Cereal grains nec,0.00000,0.000000,5340.322075,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - fallowed area - Crops nec,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.570044,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - fallowed area - Oil seeds,0.00000,0.000000,0.000000,0.000000,2446.248582,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - fallowed area - Paddy rice,19.21149,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - fallowed area - Plant-based fibers,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,18.511733,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Cropland - fallowed area - Sugar cane, sugar beet",0.00000,0.000000,0.000000,0.000000,0.000000,568.202068,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Cropland - fallowed area - Vegetables, fruit, nuts",0.00000,0.000000,0.000000,2257.034495,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - fallowed area - Wheat,0.00000,6672.175763,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - fallowed area-Cattle,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18324.672488,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - fallowed area-Meat animals nec,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - fallowed area-Pigs,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2541.425049,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - fallowed area-Poultry,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cropland - fallowed area-Raw milk,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Forest,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Permanent pastures - Grazing-Cattle,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,53944.312500,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Permanent pastures - Grazing-Meat animals nec,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Permanent pastures - Grazing-Raw milk,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\MatMat\matmat-ademe\data\4-PlaneFR\1-accounts\MatMat\3.10.2_France_2019\extensions\dom_raw_materials\F_Z.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
# exporte en csv
#df['FR'].to_excel(r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Données\Exiobase\F_x_dom_materials.xlsx")
df

region                                                                                                  France  \
category                                                                                           Agriculture
sub_category                                                                                     Primary_Crops
sector                                                                                              Paddy rice
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                             0.028992
                                               Wheat                                                  0.000000
                                               Cereal grains nec                                      0.000000
                                               Vegetables, fruit, nuts                                0.000000
                                               Oil seeds                                              0.000000
...                                                                                                        ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)           0.000000
                                               Recreational, cultural and sporting services (92)      0.000000
                                               Other services (93)                                    0.000000
                                               Private households with employed persons (95)          0.000000
                                               Extra-territorial organizations and bodies             0.000000

region                                                                                                        \
category
sub_category
sector                                                                                                 Wheat
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                           0.000000
                                               Wheat                                              841.542987
                                               Cereal grains nec                                    0.000000
                                               Vegetables, fruit, nuts                              0.000000
                                               Oil seeds                                            0.000000
...                                                                                                      ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)         0.000000
                                               Recreational, cultural and sporting services (92)    0.000000
                                               Other services (93)                                  0.000000
                                               Private households with employed persons (95)        0.000000
                                               Extra-territorial organizations and bodies           0.000000

region                                                                                                              \
category
sub_category
sector                                                                                           Cereal grains nec
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                                 0.000000
                                               Wheat                                                      0.000000
                                               Cereal grains nec                                        476.186036
                                               Vegetables, fruit, nuts                                    0.000000
                                               Oil seeds                                                  0.000000
...                                                                                                            ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)               0.000000
                                               Recreational, cultural and sporting services (92)          0.000000
                                               Other services (93)                                        0.000000
                                               Private households with employed persons (95)              0.000000
                                               Extra-territorial organizations and bodies                 0.000000

region                                                                                                                    \
category
sub_category
sector                                                                                           Vegetables, fruit, nuts
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                                       0.000000
                                               Wheat                                                            0.000000
                                               Cereal grains nec                                                0.000000
                                               Vegetables, fruit, nuts                                       1909.597843
                                               Oil seeds                                                        0.000000
...                                                                                                                  ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)                     0.000000
                                               Recreational, cultural and sporting services (92)                0.000000
                                               Other services (93)                                              0.000000
                                               Private households with employed persons (95)                    0.000000
                                               Extra-territorial organizations and bodies                       0.000000

region                                                                                                       \
category
sub_category
sector                                                                                            Oil seeds
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                          0.000000
                                               Wheat                                               0.000000
                                               Cereal grains nec                                   0.000000
                                               Vegetables, fruit, nuts                             0.000000
                                               Oil seeds                                          21.192334
...                                                                                                     ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)        0.000000
                                               Recreational, cultural and sporting services (92)   0.000000
                                               Other services (93)                                 0.000000
                                               Private households with employed persons (95)       0.000000
                                               Extra-territorial organizations and bodies          0.000000

region                                                                                                                   \
category
sub_category
sector                                                                                           Sugar cane, sugar beet
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                                           0.0
                                               Wheat                                                                0.0
                                               Cereal grains nec                                                    0.0
                                               Vegetables, fruit, nuts                                              0.0
                                               Oil seeds                                                            0.0
...                                                                                                                 ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)                         0.0
                                               Recreational, cultural and sporting services (92)                    0.0
                                               Other services (93)                                                  0.0
                                               Private households with employed persons (95)                        0.0
                                               Extra-territorial organizations and bodies                           0.0

region                                                                                                               \
category
sub_category
sector                                                                                           Plant-based fibers
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                                       0.0
                                               Wheat                                                            0.0
                                               Cereal grains nec                                                0.0
                                               Vegetables, fruit, nuts                                          0.0
                                               Oil seeds                                                        0.0
...                                                                                                             ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)                     0.0
                                               Recreational, cultural and sporting services (92)                0.0
                                               Other services (93)                                              0.0
                                               Private households with employed persons (95)                    0.0
                                               Extra-territorial organizations and bodies                       0.0

region                                                                                                       \
category
sub_category
sector                                                                                            Crops nec
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                          0.000000
                                               Wheat                                              31.665326
                                               Cereal grains nec                                   6.120449
                                               Vegetables, fruit, nuts                             0.000253
                                               Oil seeds                                           0.000442
...                                                                                                     ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)        0.000000
                                               Recreational, cultural and sporting services (92)   0.000000
                                               Other services (93)                                 0.000000
                                               Private households with employed persons (95)       0.000000
                                               Extra-territorial organizations and bodies          0.000000

region                                                                                                         \
category
sub_category                                                                                     Farm_animals
sector                                                                                                 Cattle
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                            6.133731
                                               Wheat                                               341.517327
                                               Cereal grains nec                                  1677.179590
                                               Vegetables, fruit, nuts                               2.083208
                                               Oil seeds                                             0.000000
...                                                                                                       ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)          0.000000
                                               Recreational, cultural and sporting services (92)     0.000000
                                               Other services (93)                                   0.000000
                                               Private households with employed persons (95)         0.000000
                                               Extra-territorial organizations and bodies            0.000000

region                                                                                                        \
category
sub_category
sector                                                                                                  Pigs
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                           3.246315
                                               Wheat                                               46.929348
                                               Cereal grains nec                                  387.936316
                                               Vegetables, fruit, nuts                              2.451999
                                               Oil seeds                                            0.000000
...                                                                                                      ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)         0.000000
                                               Recreational, cultural and sporting services (92)    0.000000
                                               Other services (93)                                  0.000000
                                               Private households with employed persons (95)        0.000000
                                               Extra-territorial organizations and bodies           0.000000

region                                                                                            ...  \
category                                                                                          ...
sub_category                                                                                      ...
sector                                                                                            ...
origin   region category     sub_category      sector                                             ...
domestic France Agriculture  Primary_Crops     Paddy rice                                         ...
                                               Wheat                                              ...
                                               Cereal grains nec                                  ...
                                               Vegetables, fruit, nuts                            ...
                                               Oil seeds                                          ...
...                                                                                               ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)       ...
                                               Recreational, cultural and sporting services (92)  ...
                                               Other services (93)                                ...
                                               Private households with employed persons (95)      ...
                                               Extra-territorial organizations and bodies         ...

region                                                                                                                          \
category                                                                                             Water_and_waste_treatment
sub_category                                                                                                          Landfill
sector                                                                                           Paper for treatment: landfill
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                                             0.000000
                                               Wheat                                                                  0.070367
                                               Cereal grains nec                                                      0.078053
                                               Vegetables, fruit, nuts                                                0.007680
                                               Oil seeds                                                              0.011757
...                                                                                                                        ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)                           0.000000
                                               Recreational, cultural and sporting services (92)                      0.000000
                                               Other services (93)                                                    0.000000
                                               Private households with employed persons (95)                          0.000000
                                               Extra-territorial organizations and bodies                             0.000000

region                                                                                                                                  \
category
sub_category
sector                                                                                           Plastic waste for treatment: landfill
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                                                     0.000000
                                               Wheat                                                                          0.024395

In [ ]:
PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\Module_PlaneFR\data\3.10.2\2019_World\extensions\raw_materials\d_cba.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
# exporte en csv
#df['FR'].to_excel(r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Données\Exiobase\F_x_dom_materials.xlsx")
df

region                                                     World
Y_category                                                   all
sector                                                       all
indicator
Primary Crops - Rice                                7.532864e+05
Primary Crops - Wheat                               7.640759e+05
Primary Crops - Cereals n.e.c.                      1.446088e+06
Primary Crops - Roots and tubers                    8.535042e+05
Primary Crops - Pulses                              8.541811e+04
...                                                          ...
Non-Metallic Minerals - Chemical minerals n.e.c.    2.026269e+05
Non-Metallic Minerals - Industrial minerals n.e.c   4.264276e+05
Non-Metallic Minerals - Salt                        2.714749e+05
Non-Metallic Minerals - Other non-metallic mine...  3.161830e+05
RMC                                                 9.481321e+07

[63 rows x 1 columns]

In [ ]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\MatMat\matmat-ademe\data\4-PlaneFR\Outputs\World\base-year_2019\extensions\land_use\F_x_dom.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
df_tot_exio = df['FR'].sum().sum()
df_tot_exio

np.float64(456884.4815233743)

In [ ]:
1 - df_tot_exio / df_tot_matmat

np.float64(-0.0242570833859288)