In [ ]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\MatMat\matmat-ademe\data\4-PlaneFR\Outputs_inter\gmrio_to_snac_s\3.10.2_pxp_2015\extensions\dom_water\F_x_dom.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
df_tot_matmat =df.sum(axis=0).sum()
df_tot_matmat

np.float64(3822.8172209934637)

In [8]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\MatMat\matmat-ademe\data\4-PlaneFR\1-accounts\Exiobase\3.10.2_2019\3.10.2_pxp_2019\extensions\raw_materials\F_x_dom.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
# exporte en csv
#df['FR'].to_excel(r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Données\Exiobase\F_x_dom_materials.xlsx")
df['FR']

sector,Paddy rice,Wheat,Cereal grains nec,"Vegetables, fruit, nuts",Oil seeds,"Sugar cane, sugar beet",Plant-based fibers,Crops nec,Cattle,Pigs,...,Paper for treatment: landfill,Plastic waste for treatment: landfill,Inert/metal/hazardous waste for treatment: landfill,Textiles waste for treatment: landfill,Wood waste for treatment: landfill,Membership organisation services n.e.c. (91),"Recreational, cultural and sporting services (92)",Other services (93),Private households with employed persons (95),Extra-territorial organizations and bodies
indicator,,,,,,,,,,,,,,,,,,,,,
Primary Crops - Rice,82.57,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Primary Crops - Wheat,0.00,40604.96,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Primary Crops - Cereals n.e.c.,0.00,0.00,30008.085067,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Primary Crops - Roots and tubers,0.00,0.00,0.000000,8626.170593,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Primary Crops - Pulses,0.00,0.00,0.000000,1051.299276,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Non-Metallic Minerals - Fertilizer minerals n.e.c.,0.00,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Non-Metallic Minerals - Chemical minerals n.e.c.,0.00,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Non-Metallic Minerals - Industrial minerals n.e.c,0.00,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Non-Metallic Minerals - Salt,0.00,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Non-Metallic Minerals - Other non-metallic minerals n.e.c.,0.00,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\MatMat\matmat-ademe\data\4-PlaneFR\1-accounts\MatMat\3.10.2_France_2019\extensions\dom_raw_materials\F_Z.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
# exporte en csv
#df['FR'].to_excel(r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Données\Exiobase\F_x_dom_materials.xlsx")
df

region                                                                                                  France  \
category                                                                                           Agriculture
sub_category                                                                                     Primary_Crops
sector                                                                                              Paddy rice
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                             0.028992
                                               Wheat                                                  0.000000
                                               Cereal grains nec                                      0.000000
                                               Vegetables, fruit, nuts                                0.000000
                                               Oil seeds                                              0.000000
...                                                                                                        ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)           0.000000
                                               Recreational, cultural and sporting services (92)      0.000000
                                               Other services (93)                                    0.000000
                                               Private households with employed persons (95)          0.000000
                                               Extra-territorial organizations and bodies             0.000000

region                                                                                                        \
category
sub_category
sector                                                                                                 Wheat
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                           0.000000
                                               Wheat                                              841.542987
                                               Cereal grains nec                                    0.000000
                                               Vegetables, fruit, nuts                              0.000000
                                               Oil seeds                                            0.000000
...                                                                                                      ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)         0.000000
                                               Recreational, cultural and sporting services (92)    0.000000
                                               Other services (93)                                  0.000000
                                               Private households with employed persons (95)        0.000000
                                               Extra-territorial organizations and bodies           0.000000

region                                                                                                              \
category
sub_category
sector                                                                                           Cereal grains nec
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                                 0.000000
                                               Wheat                                                      0.000000
                                               Cereal grains nec                                        476.186036
                                               Vegetables, fruit, nuts                                    0.000000
                                               Oil seeds                                                  0.000000
...                                                                                                            ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)               0.000000
                                               Recreational, cultural and sporting services (92)          0.000000
                                               Other services (93)                                        0.000000
                                               Private households with employed persons (95)              0.000000
                                               Extra-territorial organizations and bodies                 0.000000

region                                                                                                                    \
category
sub_category
sector                                                                                           Vegetables, fruit, nuts
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                                       0.000000
                                               Wheat                                                            0.000000
                                               Cereal grains nec                                                0.000000
                                               Vegetables, fruit, nuts                                       1909.597843
                                               Oil seeds                                                        0.000000
...                                                                                                                  ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)                     0.000000
                                               Recreational, cultural and sporting services (92)                0.000000
                                               Other services (93)                                              0.000000
                                               Private households with employed persons (95)                    0.000000
                                               Extra-territorial organizations and bodies                       0.000000

region                                                                                                       \
category
sub_category
sector                                                                                            Oil seeds
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                          0.000000
                                               Wheat                                               0.000000
                                               Cereal grains nec                                   0.000000
                                               Vegetables, fruit, nuts                             0.000000
                                               Oil seeds                                          21.192334
...                                                                                                     ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)        0.000000
                                               Recreational, cultural and sporting services (92)   0.000000
                                               Other services (93)                                 0.000000
                                               Private households with employed persons (95)       0.000000
                                               Extra-territorial organizations and bodies          0.000000

region                                                                                                                   \
category
sub_category
sector                                                                                           Sugar cane, sugar beet
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                                           0.0
                                               Wheat                                                                0.0
                                               Cereal grains nec                                                    0.0
                                               Vegetables, fruit, nuts                                              0.0
                                               Oil seeds                                                            0.0
...                                                                                                                 ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)                         0.0
                                               Recreational, cultural and sporting services (92)                    0.0
                                               Other services (93)                                                  0.0
                                               Private households with employed persons (95)                        0.0
                                               Extra-territorial organizations and bodies                           0.0

region                                                                                                               \
category
sub_category
sector                                                                                           Plant-based fibers
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                                       0.0
                                               Wheat                                                            0.0
                                               Cereal grains nec                                                0.0
                                               Vegetables, fruit, nuts                                          0.0
                                               Oil seeds                                                        0.0
...                                                                                                             ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)                     0.0
                                               Recreational, cultural and sporting services (92)                0.0
                                               Other services (93)                                              0.0
                                               Private households with employed persons (95)                    0.0
                                               Extra-territorial organizations and bodies                       0.0

region                                                                                                       \
category
sub_category
sector                                                                                            Crops nec
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                          0.000000
                                               Wheat                                              31.665326
                                               Cereal grains nec                                   6.120449
                                               Vegetables, fruit, nuts                             0.000253
                                               Oil seeds                                           0.000442
...                                                                                                     ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)        0.000000
                                               Recreational, cultural and sporting services (92)   0.000000
                                               Other services (93)                                 0.000000
                                               Private households with employed persons (95)       0.000000
                                               Extra-territorial organizations and bodies          0.000000

region                                                                                                         \
category
sub_category                                                                                     Farm_animals
sector                                                                                                 Cattle
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                            6.133731
                                               Wheat                                               341.517327
                                               Cereal grains nec                                  1677.179590
                                               Vegetables, fruit, nuts                               2.083208
                                               Oil seeds                                             0.000000
...                                                                                                       ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)          0.000000
                                               Recreational, cultural and sporting services (92)     0.000000
                                               Other services (93)                                   0.000000
                                               Private households with employed persons (95)         0.000000
                                               Extra-territorial organizations and bodies            0.000000

region                                                                                                        \
category
sub_category
sector                                                                                                  Pigs
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                           3.246315
                                               Wheat                                               46.929348
                                               Cereal grains nec                                  387.936316
                                               Vegetables, fruit, nuts                              2.451999
                                               Oil seeds                                            0.000000
...                                                                                                      ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)         0.000000
                                               Recreational, cultural and sporting services (92)    0.000000
                                               Other services (93)                                  0.000000
                                               Private households with employed persons (95)        0.000000
                                               Extra-territorial organizations and bodies           0.000000

region                                                                                            ...  \
category                                                                                          ...
sub_category                                                                                      ...
sector                                                                                            ...
origin   region category     sub_category      sector                                             ...
domestic France Agriculture  Primary_Crops     Paddy rice                                         ...
                                               Wheat                                              ...
                                               Cereal grains nec                                  ...
                                               Vegetables, fruit, nuts                            ...
                                               Oil seeds                                          ...
...                                                                                               ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)       ...
                                               Recreational, cultural and sporting services (92)  ...
                                               Other services (93)                                ...
                                               Private households with employed persons (95)      ...
                                               Extra-territorial organizations and bodies         ...

region                                                                                                                          \
category                                                                                             Water_and_waste_treatment
sub_category                                                                                                          Landfill
sector                                                                                           Paper for treatment: landfill
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                                             0.000000
                                               Wheat                                                                  0.070367
                                               Cereal grains nec                                                      0.078053
                                               Vegetables, fruit, nuts                                                0.007680
                                               Oil seeds                                                              0.011757
...                                                                                                                        ...
import   RoW    Oth_services Business_services Membership organisation services n.e.c. (91)                           0.000000
                                               Recreational, cultural and sporting services (92)                      0.000000
                                               Other services (93)                                                    0.000000
                                               Private households with employed persons (95)                          0.000000
                                               Extra-territorial organizations and bodies                             0.000000

region                                                                                                                                  \
category
sub_category
sector                                                                                           Plastic waste for treatment: landfill
origin   region category     sub_category      sector
domestic France Agriculture  Primary_Crops     Paddy rice                                                                     0.000000
                                               Wheat                                                                          0.024395

In [17]:
PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\Module_PlaneFR\data\3.10.2\2019_World\extensions\raw_materials\d_cba.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
# exporte en csv
#df['FR'].to_excel(r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Données\Exiobase\F_x_dom_materials.xlsx")
df

region                                                     World
Y_category                                                   all
sector                                                       all
indicator
Primary Crops - Rice                                7.532864e+05
Primary Crops - Wheat                               7.640759e+05
Primary Crops - Cereals n.e.c.                      1.446088e+06
Primary Crops - Roots and tubers                    8.535042e+05
Primary Crops - Pulses                              8.541811e+04
...                                                          ...
Non-Metallic Minerals - Chemical minerals n.e.c.    2.026269e+05
Non-Metallic Minerals - Industrial minerals n.e.c   4.264276e+05
Non-Metallic Minerals - Salt                        2.714749e+05
Non-Metallic Minerals - Other non-metallic mine...  3.161830e+05
RMC                                                 9.481321e+07

[63 rows x 1 columns]

In [ ]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\PlaneFR\Code\MatMat\matmat-ademe\data\4-PlaneFR\Outputs\World\base-year_2019\extensions\land_use\F_x_dom.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
df_tot_exio = df['FR'].sum().sum()
df_tot_exio

np.float64(456884.4815233743)

In [ ]:
1 - df_tot_exio / df_tot_matmat

np.float64(-0.0242570833859288)