In [43]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\MatMat\260609-datapack\data\4-PlanéFR\Outputs\Monde\base-year_2019\extensions\ghg_emissions\F_Y_tot.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df_1 = pickle.load(f)
mask_region = df_1.columns.get_level_values("region").isin(df)
df_1 = df_1.loc[:, mask_region]
df_1

Empty DataFrame
Columns: []
Index: [(ghg_combustion, CO2), (ghg_combustion, CH4), (ghg_combustion, N2O), (ghg_combustion, SF6), (ghg_combustion, HFC), (ghg_combustion, PFC), (ghg_other, CO2), (ghg_other, CH4), (ghg_other, N2O), (ghg_other, SF6), (ghg_other, HFC), (ghg_other, PFC)]

In [5]:
import pickle
import pandas as pd

PATHS = [
    r"C:\Users\Arnaud\Documents\PlaneFR\data\3.10.2\2019_Europe_27\extensions\ghg_emissions\F_Y_tot.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
display(df.sum())

region  sector
Europe  all       660.120746
dtype: object

In [1]:
import pymrio

In [14]:
exio = pymrio.parse_exiobase3(r"C:\Users\Arnaud\Documents\CIRED\MatMat\260609-datapack\data\01-sources_public\exiobase\3.10.2\IOT_2019_pxp.zip")

In [15]:
exio.calc_all()

In [2]:
exio_39 = pymrio.parse_exiobase3(r"C:\Users\Arnaud\Documents\CIRED\MatMat\260609-datapack\data\01-sources_public\exiobase\3.9.6\IOT_2015_pxp.zip")

In [25]:
df = exio.air_emissions.F_Y.T.groupby(level="region").sum().T
eu_regions = df.columns.get_level_values("region").unique()[:27]
mask_region = df.columns.get_level_values("region").isin(eu_regions)
df = df.loc[:, mask_region]
df

region,AT,AU,BE,BG,BR,CA,CH,CN,CY,CZ,...,GR,HR,HU,ID,IE,IN,IT,JP,KR,LT
stressor,,,,,,,,,,,,,,,,,,,,,
As - combustion - air,32.008235,6.429608e+01,4.917600e+01,28.116530,8.948263e+02,1.160577e+02,1.903354e+01,6.906104e+03,5.091639,1.103624e+02,...,3.341384e+01,22.747344,4.286644e+01,4.662307e+02,3.069652e+02,6.719599e+03,1.629103e+02,2.148723e+03,5.584043e+02,15.060374
B(a)P - combustion - air,2310.117567,6.739933e+03,2.422304e+03,4657.174015,1.234015e+05,1.178451e+04,1.016193e+03,7.281805e+05,170.761126,1.130410e+04,...,3.564677e+03,4426.122253,7.341571e+03,2.623295e+04,8.543517e+03,7.123572e+05,2.857891e+04,5.371639e+04,1.410903e+04,2002.409354
B(b)F - combustion - air,2486.037531,7.064212e+03,2.712479e+03,5209.197975,1.296671e+05,1.242724e+04,1.112134e+03,8.864269e+05,199.129186,1.343911e+04,...,3.840481e+03,4658.805229,7.957824e+03,2.798196e+04,1.057561e+04,8.000381e+05,3.001366e+04,6.233992e+04,1.645480e+04,2323.609289
B(k)F - combustion - air,1413.985385,4.170515e+03,1.446150e+03,2836.974331,7.629599e+04,7.258154e+03,6.113009e+02,4.331542e+05,99.011926,6.775312e+03,...,2.178141e+03,2736.285456,4.507480e+03,1.602633e+04,4.853069e+03,4.327893e+05,1.767196e+04,3.068955e+04,8.049824e+03,1207.663328
CH4 - combustion - air,872796.553571,4.874691e+06,2.067286e+06,799579.896548,6.666923e+06,1.085965e+07,1.120742e+06,6.587515e+08,116315.805780,5.109951e+06,...,1.472339e+06,317440.830419,1.339932e+06,9.818885e+06,3.936469e+06,3.210310e+07,1.201162e+07,2.061979e+07,8.787543e+06,438226.153304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CO2 - waste - fossil - air,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,...,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
NH3 - waste - air,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,...,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
NOX - waste - air,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,...,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
PM2.5 - waste - air,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,...,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
SOx - waste - air,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,...,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000

In [24]:
mask_region

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [11]:
#export en csv
F_Y_agg.to_pickle(r"C:\Users\Arnaud\Documents\CIRED\MatMat\260609-datapack\data\4-PlanéFR\Outputs\Monde\base-year_2019\extensions\air_emissions\F_Y_tot.pkl")

In [37]:
PATHS = [
    "data/3.10.2/base_year_2019/dom_ghg_combustion/d_cba_k.pkl",
    "data/3.10.2/base_year_2019/dom_ghg_combustion/d_cba.pkl",
]

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)

    # Sum all rows into a single row named "CO2"
    df = df.sum().rename("CO2").to_frame().T
    df.index.name = "indicator"

    with open(path, "wb") as f:
        pickle.dump(df, f)

    print(f"Done: {path}  shape={df.shape}  index={df.index.names}")



PATHS = [
    "data/3.10.2/base_year_2019/dom_raw_materials/d_cba_k.pkl",
    "data/3.10.2/base_year_2019/imp_raw_materials/d_cba_k.pkl",
    "data/3.10.2/base_year_2019/dom_raw_materials/d_cba.pkl",
    "data/3.10.2/base_year_2019/imp_raw_materials/d_cba.pkl"
]

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)

    # Sum all rows into a single row named "CO2"
    df = df.sum().rename("RMC").to_frame().T
    df.index.name = "indicator"

    with open(path, "wb") as f:
        pickle.dump(df, f)

    print(f"Done: {path}  shape={df.shape}  index={df.index.names}")

region                France                                                  \
Y_category        Households
Y_sub_category   Residential
category         Agriculture
sub_category   Primary_Crops
sector            Paddy rice Wheat Cereal grains nec Vegetables, fruit, nuts
indicator
RMC                      0.0   0.0               0.0                     0.0

region                                                                        \
Y_category
Y_sub_category
category
sub_category
sector         Oil seeds Sugar cane, sugar beet Plant-based fibers Crops nec
indicator
RMC                  0.0                    0.0                0.0       0.0

region                            ...                                \
Y_category                        ...                       Exports
Y_sub_category                    ...                             E
category                          ...     Water_and_waste_treatment
sub_category   Farm_animals       ...                      Landfill
sector               Cattle Pigs  ... Paper for treatment: landfill
indicator                         ...
RMC                     0.0  0.0  ...                      2.959555

region                                                \
Y_category
Y_sub_category
category
sub_category
sector         Plastic waste for treatment: landfill
indicator
RMC                                         0.896504

region                                                              \
Y_category
Y_sub_category
category
sub_category
sector         Inert/metal/hazardous waste for treatment: landfill
indicator
RMC                                                      6.705771

region                                                 \
Y_category
Y_sub_category
category
sub_category
sector         Textiles waste for treatment: landfill
indicator
RMC                                          0.541991

region                                             \
Y_category
Y_sub_category
category
sub_category
sector         Wood waste for treatment: landfill
indicator
RMC                                      1.096009

region                                                       \
Y_category
Y_sub_category
category                                       Oth_services
sub_category                              Business_services
sector         Membership organisation services n.e.c. (91)
indicator
RMC                                               11.991706

region                                                            \
Y_category
Y_sub_category
category
sub_category
sector         Recreational, cultural and sporting services (92)
indicator
RMC                                                   429.226336

region                              \
Y_category
Y_sub_category
category
sub_category
sector         Other services (93)
indicator
RMC                      35.899755

region                                                        \
Y_category
Y_sub_category
category
sub_category
sector         Private households with employed persons (95)
indicator
RMC                                                17.570919

region
Y_category
Y_sub_category
category
sub_category
sector         Extra-territorial organizations and bodies
indicator
RMC                                                   0.0

[1 rows x 1200 columns]

In [ ]:
PATHS = [
    "C:\\Users\\Arnaud\\Documents\\CIRED\\MatMat\\260609-datapack\\data\\4-PlanéFR\\Outputs\\Europe\\base-year_2019\\extensions\\dom_biogeochemical\\d_cba.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)

df
#df_dom_ghg = df_dom_ghg.drop(columns='Exports', level='Y_category')
#df_dom_ghg.sum(axis=1).sum()

NameError: name 'pickle' is not defined

In [98]:
PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\MatMat\260609-datapack\data\3-workshops\1-accounts\MatMat\3.10.2_France_2015\extensions\imp_raw_materials\d_cba_k.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df_imp_ghg = pickle.load(f)

df_imp_ghg = df_imp_ghg.drop(columns='Exports', level='Y_category')
df_imp_ghg.sum(axis=1).sum()/1e3

np.float64(688.5152536215038)

In [99]:
PATHS = [
    r"C:\Users\Arnaud\Documents\CIRED\MatMat\260609-datapack\data\3-workshops\1-accounts\MatMat\3.10.2_France_2015\extensions\dom_raw_materials\d_cba_k.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df_imp_ghg = pickle.load(f)

df_imp_ghg = df_imp_ghg.drop(columns='Exports', level='Y_category')
df_imp_ghg.sum(axis=1).sum()/1e3

np.float64(403.21255434547595)

In [89]:
PATHS = [
    "C:\\Users\\Arnaud\\Documents\\PlaneFR\\data\\3.10.2\\base-year_2019\\extensions\\dom_ghg_combustion\\d_cba_k.pkl",
]   

for path in PATHS:
    with open(path, "rb") as f:
        df_dom_ghg_combustion = pickle.load(f)

df_dom_ghg_combustion = df_dom_ghg_combustion.drop(columns='Exports', level='Y_category')
df_dom_ghg_combustion.sum(axis=1).sum()

np.float64(218.97903407409848)

In [42]:
import os 

PATHS = [
    "data/3.10.2/base_year_2019/dom_ghg_combustion/d_cba_k.pkl",
    "data/3.10.2/base_year_2019/dom_ghg_combustion/d_cba.pkl",
]

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)

    if "CO2" not in df.index:
        # Sum all rows into a single row named "CO2"
        df = df.sum().rename("CO2").to_frame().T
        df.index.name = "indicator"

        with open(path, "wb") as f:
            pickle.dump(df, f)

    print(f"Done: {path}  shape={df.shape}  index={df.index.names}")

    imp_path = path.replace("dom", "imp")
    os.makedirs(os.path.dirname(imp_path), exist_ok=True)
    df_zeros = df * 0
    with open(imp_path, "wb") as f:
        pickle.dump(df_zeros, f)

Done: data/3.10.2/base_year_2019/dom_ghg_combustion/d_cba_k.pkl  shape=(1, 1000)  index=['indicator']
Done: data/3.10.2/base_year_2019/dom_ghg_combustion/d_cba.pkl  shape=(1, 1200)  index=['indicator']

In [43]:
   df_zeros

region                France                                                  \
Y_category        Households
Y_sub_category   Residential
category         Agriculture
sub_category   Primary_Crops
sector            Paddy rice Wheat Cereal grains nec Vegetables, fruit, nuts
indicator
CO2                      0.0   0.0               0.0                     0.0

region                                                                        \
Y_category
Y_sub_category
category
sub_category
sector         Oil seeds Sugar cane, sugar beet Plant-based fibers Crops nec
indicator
CO2                  0.0                    0.0                0.0       0.0

region                            ...                                \
Y_category                        ...                       Exports
Y_sub_category                    ...                             E
category                          ...     Water_and_waste_treatment
sub_category   Farm_animals       ...                      Landfill
sector               Cattle Pigs  ... Paper for treatment: landfill
indicator                         ...
CO2                     0.0  0.0  ...                           0.0

region                                                \
Y_category
Y_sub_category
category
sub_category
sector         Plastic waste for treatment: landfill
indicator
CO2                                              0.0

region                                                              \
Y_category
Y_sub_category
category
sub_category
sector         Inert/metal/hazardous waste for treatment: landfill
indicator
CO2                                                           0.0

region                                                 \
Y_category
Y_sub_category
category
sub_category
sector         Textiles waste for treatment: landfill
indicator
CO2                                               0.0

region                                             \
Y_category
Y_sub_category
category
sub_category
sector         Wood waste for treatment: landfill
indicator
CO2                                           0.0

region                                                       \
Y_category
Y_sub_category
category                                       Oth_services
sub_category                              Business_services
sector         Membership organisation services n.e.c. (91)
indicator
CO2                                                     0.0

region                                                            \
Y_category
Y_sub_category
category
sub_category
sector         Recreational, cultural and sporting services (92)
indicator
CO2                                                          0.0

region                              \
Y_category
Y_sub_category
category
sub_category
sector         Other services (93)
indicator
CO2                            0.0

region                                                        \
Y_category
Y_sub_category
category
sub_category
sector         Private households with employed persons (95)
indicator
CO2                                                      0.0

region
Y_category
Y_sub_category
category
sub_category
sector         Extra-territorial organizations and bodies
indicator
CO2                                                   0.0

[1 rows x 1200 columns]

In [41]:
PATHS = [
    "data/3.10.2/base_year_2019/dom_ghg_combustion/d_cba_k.pkl",
    "data/3.10.2/base_year_2019/dom_ghg_combustion/d_cba.pkl",
]

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)
# Sum all rows into a single row named "CO2"
df = df.sum().rename("CO2").to_frame().T
df.index.name = "indicator"
if "CO2" in df.index:
    print(df.index)

Index(['CO2'], dtype='str', name='indicator')

In [36]:
PATHS = [
    "data/3.10.2/base_year_2019/dom_ghg_emissions/unit.pkl",
]

for path in PATHS:
    with open(path, "rb") as f:
        df = pickle.load(f)

df

variable               unit
source         gas
ghg_combustion CO2  MtCO2eq
               CH4  MtCO2eq
               N2O  MtCO2eq
               SF6  MtCO2eq
               HFC  MtCO2eq
               PFC  MtCO2eq
ghg_other      CO2  MtCO2eq
               CH4  MtCO2eq
               N2O  MtCO2eq
               SF6  MtCO2eq
               HFC  MtCO2eq
               PFC  MtCO2eq

In [ ]:
# Drop first 4 column index levels
    df = df.droplevel(list(range(4)), axis=1)
    # Rename 2nd column level 'sector' -> 'indicator'
    df.columns.names = [df.columns.names[0], "indicator"]